### ISSUE TITLE
[FEATURE] Dynamic top navbar-search box

### ISSUE THREAD

**Issue by saviemedia** [jeroennoten/Laravel-AdminLTE#1014]
### Is your request related to a problem? Please describe.
I would like the top navbar-search to stay in the same page and open a dynamic/responsive box that update itself when we write.

### Describe the solution you'd like
Like that:
![image](https://user-images.githubusercontent.com/25592988/141368963-4fd4668c-f985-4c0d-aeab-6b51c3d8530e.png)

Is it already possible? If not, how would you implement it?

Much thanks in advance!

**Comment by Shidersz** [comment]
The package do not offer such facility right now. I think [Laravel Livewire](https://laravel-livewire.com/) is what you need to implement something like that...

**Comment by saviemedia** [comment]
Thank you for your quick reply @Shidersz !

**Comment by Shidersz** [comment]
@saviemedia Note you can always [publish the package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) in order to make such customizations. The current search bar for the navbar is defined here:

https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/partials/navbar/menu-item-search-form.blade.php

See documentation on [Special Menu Items / Navbar Search](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Special-Menu-Items#navbar-search)
