### ISSUE TITLE
Bootstrap 5 support for Laravel-AdminLTE

### ISSUE THREAD

**Issue by robinflyhigh** [jeroennoten/Laravel-AdminLTE#1015]
Is there any roadmap for Bootstrap 5 support for AdminLTE.

**Comment by Shidersz** [comment]
There is a currently development branch for **Bootstrap 5** on the underlying [AdminLTE v.4](https://github.com/ColorlibHQ/AdminLTE). Once the underlying package supports it with an official version, we will need some time and a lot of work to update the used **AdminLTE** package version here, since it will contain lot of major and breaking changes... On summary, there is no plan for **Bootstrap 5** here in the short time.

**Comment by romanstingler** [comment]
@dfsmania It seems that https://github.com/ColorlibHQ/AdminLTE has a working branch 
but you have no v4 branch yet. will this be on the schedule ??
