### ISSUE TITLE
[QUESTION] Datatables AJAX Jquery

### ISSUE THREAD

**Issue by thyk123** [jeroennoten/Laravel-AdminLTE#1033]
How to use AJAX in datatables here?, i can't access attribute datatables get error message DataTables warning: table id={id} - Cannot reinitialise DataTable and when I try see in inspect elements there already script that select the attributes of the datatables

**Comment by thyk123** [comment]
I added "destroy: true", property at my script datatables initiator so the datatable script that already created before by adminlte template get skipped

**Comment by Shidersz** [comment]
@thyk123 If you are talking about the [Datatables Blade Component](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Tool-Components#datatables), then documentation is available there. For most basic configurations, you can use the `config` property of the component. And yes, initialization is already done by the component, because it adds some default configuration to the plugin, plus the `dom` configuration if you enable the buttons extension.

What I usually do in these cases, is to get data making an `ajax` request to the source first, then you can format and put that data in to the under `data` property of the `config` attribute, see the examples.
