### ISSUE TITLE
[QUESTION]  is there a way to use vue3 in laravel 8 and this template without publish it?

### ISSUE THREAD

**Issue by TSBrandsGroup** [jeroennoten/Laravel-AdminLTE#1061]
if there it is, how?

**Comment by Shidersz** [comment]
Please provide more information.
- What have you tried?
- What stops you from going forward?
- What you mean without publish it?

**Comment by TSBrandsGroup** [comment]
thank you @Shidersz...
i`m triying to use vue 3 in a laravel 8 project using this greate template...

the only thing that i've tried is put a <div id="app></div> inside a blade view and there call my vue component... 
doesn't work...
i know that vue requires to put tha app id on the div body, so i want to know if is there a way to do it without publish the main views of the template

https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization

**Comment by Shidersz** [comment]
I do not have experience with `Vue`, but on the [introduction examples](https://vuejs.org/guide/introduction.html#what-is-vue) there is nothing saying you need a `<div id="app">` inside the body tag. On their first example:

```js
createApp({
  data() {
    return {
      count: 0
    }
  }
}).mount('#app')

````
```html
<div id="app">
  <button @click="count++">
    Count is: {{ count }}
  </button>
</div>
````
They show you need to create a dom element with an id attribute, the name may be other than `app`, and then they target it from the `Vue` framework with with `mount('#app')` or the ID you have choosen for your element.

Be sure to include `Vue.js` as a plugin, if you haven't done it => [Plugins Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration)

**Comment by TSBrandsGroup** [comment]
when you install vue in a laravel project using composer require laravel/ui and php artisan ui vue, automatically is created a vue component example: 
<template>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Example Component</div>

                    <div class="card-body">
                        I'm an example component.
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

and a js (app.js) file in which you should add all of your vue components, 'globally'...
this file defines the main DOM element in which all of the components will be

require('./bootstrap');
window.Vue = require('vue').default;

Vue.component('example-component', require('./components/ExampleComponent.vue').default);
// more vue components and their routes...

const app = new Vue({
    el: '#app',
});

and you can call these components in any view by including their defined tag in it :
    <example-component></example-component>

this way of install vue do not needs to call a cdn of vue.js and makes to work with laravel easier...
that's why it was my question...

i try already to include vue as a pluggin withoput success...
I decided to use livewire instead of vue, but it would be nice if you included support to use AdminLTE with vue...
thanks

**Comment by Shidersz** [comment]
@TSBrandsGroup If the file you are talking is `resources/app/app.js` I think you will need to use and enable `Laravel Mix` on this package. You may check the logic that is followed on [master.blade.php](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/master.blade.php) when this is enabled (however, note the plugins config won't be used anymore).

You may also check already opened/closed issues for some help: https://github.com/jeroennoten/Laravel-AdminLTE/issues?q=is%3Aissue+laravel+mix+

The alternative to the previously mentioned is to include `Vue.js` as a plugin and check there is no errors present on the browser's console.

Once you are sure **Vue** is correctly integrated and there are no errors, have you tried to create a `Vue` application using other `dom` targets different form `#app`. Maybe:

```js
const app = new Vue({
    el: 'body',
});

const app = new Vue({
    el: '.wrapper',
});
```

Or you may define a base layout for all your views as:

```blade
@extends('adminlte::page')

{{-- Page Content Body --}}
@section('content')
    <div id="app">
        @yield('content_vue')
    </div>
@stop

{{-- Page Footer --}}
@section('footer')
    <p>My common footer..</p>
@stop

{{-- Extra JS --}}

@push('js')
<script>
    const app = new Vue({
        el: '#app',
    });
</script>
@endpush
```

Then all your blade definitions will extend this blade layout.

For the moment, I can't help you anymore, because I do not have experience using `Vue` or `Laravel Mix`. However it will be nice to see someone making an effort integrating and documenting the steps to be followed.

**Comment by TSBrandsGroup** [comment]
@Shidersz you’re right it needs to use Laravel mix... thank you very much, and if my work allows me I will try to do these steps but with my personal github account...
