### ISSUE TITLE
[BUG] Datatable $config with javascript function

### ISSUE THREAD

**Issue by abudawud** [jeroennoten/Laravel-AdminLTE#1108]
### Describe the bug

In `<x-adminlte-datatable />` i can configure datatable options by passing the options to `$config`. everything going well till i need to configure datatable with options that contain javascript function.

### Steps To Reproduce

**Config**

```php
@php 
$config = [
   ...
   ,
   "columnDefs" = [
     "targets" => 2,
     "render" => "function(data,type,full,meta) {
    }",
   ],
]
@endphp
```

1. Create adminlte datatable blade component with above config
2. See error

### Expected behavior

I can configure datatable options that contain js function

### Environment

Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | 9.x
| Project | -
| OS      | `5.10.117-1-MANJARO #1 SMP PREEMPT Wed May 18 09:22:50 UTC 2022 x86_64 GNU/Linux`

**Thanks**

**Comment by dfsmania** [comment]
@abudawud Javascript code inside the configuration options is not supported by the **Datatables component**. Any idea or workaround for this problem will be welcome.

In these cases, you may try to initialize all the `Datatable` from Javascript. Take note you will need to [destroy](https://datatables.net/reference/api/destroy()) the `Datatable` before initialization, since the underlying component already initializes it.

**Comment by technofection-rakesh** [comment]
I had the same issue and here is a quick and really bad solution (but works!)

This is the modified initialization code of datatable inside the component (datatable.blade.php)

$(() => {
        @php
            $strConfig = json_encode($config);
            $tmp = preg_replace('/"(function[\s]?\([^)]+\)[\s]?{[^"]+})"/', '${1}', $strConfig);
        @endphp
        $('#{{ $id }}').DataTable( @php echo str_replace('\r\n', '', $tmp); @endphp );
    })

**Comment by stz184** [comment]
I have extended the solution of @technofection-rakesh a little bit to support a wider range of function definitions, for example arrow functions. 

To use it, you need to follow just 3 simple steps:
1. Create a new blade component `app/View/Components/Tools/ExtendedDatatable.php`
```php
<?php

namespace App\View\Components\Tools;

use JeroenNoten\LaravelAdminLte\View\Components\Tool\Datatable;

class ExtendedDatatable extends Datatable
{
    public function render()
    {
        return view('components.tools.extended-datatable');
    }

}
```
2. Create a new blade template based on [resources/views/components/tool/datatable.blade.php](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/components/tool/datatable.blade.php). Just copy the whole template contents in a new file `resources/views/components/tools/extended-datatable.blade.php` and change the js block after `{{-- Add plugin initialization and configuration code --}}` comment like this:

```blade
@push('js')
    <script>

        $(() => {
            @php
                $strConfig = json_encode($config, JSON_PRETTY_PRINT);
                $strConfig = preg_replace_callback(
                    '/("render":\s*"\s*)(.*)"/',
                    function ($matches) {
                        return '"render": ' . stripslashes(str_replace(['\r', '\n', '\t'], ["\r", "\n", "\t"], $matches[2]));
                    },
                    $strConfig
                );
            @endphp
            $('#{{ $id }}').DataTable({!! $strConfig !!});
        });

    </script>
@endpush
```
3. Use `<x-tools.extended-datatable><x-tools.extended-datatable>` component instead of `<x-adminlte-datatable />` in your blade views :)

ENJOY :)
