### ISSUE TITLE
[Advice] - how do you auto add your plugins?

### ISSUE THREAD

**Issue by sidewaysglance** [jeroennoten/Laravel-AdminLTE#1134]
So when I develop using this package I will sometimes need to add a new plugin, for e.g.:
`php artisan adminlte:plugins install --plugin=datatables`

With database migrations, you do a `git pull` and then `artisan migrate` and you're done.

What do you do for adding new plugins & things like that, so that you don't forget & the task is done automatically? Another migration?

**Comment by dfsmania** [comment]
A few notes:

> So when I develop using this package I will sometimes need to add a new plugin, for e.g.:
> `php artisan adminlte:plugins install --plugin=datatables`

That command is only useful to install the set of plugins that comes with the `AdminLTE` package, you may check the list of those plugins as explained [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration#install-a-plugin-with-the-artisan-command). The plugins are installed inside the `public/vendor` folder. So, for other plugins that do not come with the `AdminLTE` package you will need to manually copy the files inside the `public/vendor` folder. However, if you are planning to use plugins from a `CDN` you may avoid any local installation inside the `public/vendor` folder, since the plugins will now be delivered from remote servers.

Now, once a plugin is installed inside the `public/vendor` folder, or you have chose to use a `CDN`, you need to setup it inside the `adminlte.php` config file, as explained [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration). On the plugin configuration you may chose to activate it to be included in all pages. If you do not need a plugin to be available in all your blade files, then set that option to `false` and use the directive `@section('plugins.PluginName', true)` at the top of the blade files that requires the plugin.

> With database migrations, you do a `git pull` and then `artisan migrate` and you're done.

I'm not really sure why are you using those commands, `git pull` is used to get changes from a remote repository and `php artisan migrate` is used to run database migrations.

> What do you do for adding new plugins & things like that, so that you don't forget & the task is done automatically? Another migration?

Not sure if there is any option to automate the procedure. In my case, I just follow the local installation option manually.

**Comment by rightwayround** [comment]
Thanks for your input.

I prefer not to use CDNs as I like to minimise points of failure, plus I keep a tight CSP policy.

I should have explained my workflow better - I want to implement a CICD methodology at some point, but for now:

1. I use my laptop for local development
2. then commit & merge to master branch & push to my git repository
3. then log in to the production server
4. `git pull`
5. `artisan migrate`
6. ... and have forgotten to add plugins as required, plus maybe other tasks that need running, such as Laravel/Scout index updates, custom commands that need running etc etc

I have not decided how to automate any additional steps, but feel that if I can hook them into the migrate command, it might be better as that is a task I will always run when updating production.

**Comment by dfsmania** [comment]
If the `public` folder of your `Laravel` project is under the version control and all your plugins files resides there, then when you follow the procedure to add/configure a new plugin, just commit the new changes and files. In that case, `git pull` should be enough.

Usually, I follow the previous procedure without any problems. I only execute `php artisan migrate` when there is a database change, and also `composer install` when the packages dependencies are updated (i.e. there are changes uploaded to the `composer.lock` file).
