### ISSUE TITLE
How can I customize and regenerate my adminlte.min.css?

### ISSUE THREAD

**Issue by caterinahouse** [jeroennoten/Laravel-AdminLTE#1146]
Hi to everybody!

Thanks a lot for this great tool!

I would need to change the AdminLTE CSS to customize some colors, etc. I have read the issue #502 but I am not getting clear the information.

I have the folder /vendor/almasaeed2010/adminlte/build/ with some scss files. Should I modify here what I need? How do I generate again the adminlte.min.css file?

Thanks in advance

**Comment by dfsmania** [comment]
Hi @caterinahouse , I hope the next summary helps you understand how this package uses the `AdminLTE` template.

1. When this package is installed, the distribution files from the required version of the `AdminLTE` package are copied from the `vendor/almasaeed2010/adminlte/dist/` to `public/vendor/adminlte/dist/`.
2. Then, the package uses the `AdminLTE` files available on `public/vendor/adminlte/dist/` (including `adminlte.min.css` and `adminlte.min.js`)

For your goal, I think you will have to clone, change and re-build a customized version of [AdminLTE package](https://github.com/ColorlibHQ/AdminLTE). Once the new distribution files are generated for your customized version of `AdminLTE`, you may copy those files to the `public/vendor/adminlte/dist/` of your `Laravel` project in order to replace the existing ones.
