### ISSUE TITLE
[BUG] With select 2

### ISSUE THREAD

**Issue by alexandre-1992** [jeroennoten/Laravel-AdminLTE#1153]
Hello 
I install adminlte3.2 on my laravel 8 project.
I try to use select2 with multiple choose.
But when a put select2 and add javascript code my select style don't change.
I show you Screenshot  

![image](https://user-images.githubusercontent.com/58185779/207598407-432f0502-e6bd-4fe1-bcc3-8b5e96989bb5.png)

Please can you help me please?

Regards

**Comment by dfsmania** [comment]
@alexandre-1992 please, attach some example of your code...

**Comment by alexandre-1992** [comment]
my blade code
![image](https://user-images.githubusercontent.com/58185779/207606622-616efebb-1f0a-4279-9646-68f4513ae20c.png)

![image](https://user-images.githubusercontent.com/58185779/207606728-24683c52-b5a3-4f7b-a62d-89847ee1d269.png)

my bootstraap.js

![image](https://user-images.githubusercontent.com/58185779/207607982-8713ff49-00bf-453a-9cab-73615e0156b2.png)


my app.css

![image](https://user-images.githubusercontent.com/58185779/207608761-96997b2e-befd-4e23-99cc-db223afa942e.png)

**Comment by dfsmania** [comment]
Is there any reason you are not using the next documentation to include the plugins?

https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration

I've been using that way since long time and it worked nicely for me.

TIP: Use your browser's inspector to check is the `CSS` and `JS` files of the plugin is included in the rendered `HTML`, that should be your first check...

**Comment by dfsmania** [comment]
Closed, no feedback
