### ISSUE TITLE
It is not possible to replace the nabber logo.

### ISSUE THREAD

**Issue by marquezmiguel** [jeroennoten/Laravel-AdminLTE#1156]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | 9
| Project Version         | 3

### Current Behavior

I am having problems trying to change the default logo image in nabber.

When I replace the AdminLTELogo.png image with a completely different image but keeping the name AdminLTELogo.png, the original default image is still displayed in AdminLTE.

When I want to use another image file name for example mynewlogo.png and I replace its path in the adminlte.php file ( 'logo_img' => 'vendor/adminlte/dist/img/mynewlogo.png) the browser does not recognize the image even if the file exists in the stipulated folder.

### Expected Behavior

the image I have changed should appear in the browser.

### Steps to Reproduce

1: go to the adminlte.php file located in the config folder
2: Locate the following line: 'logo_img' => 'vendor/adminlte/dist/img/AdminLTELogo.png',
3: Replace "AdminLTE.png" with the name of the new image file, or rename the new image file to "AdminLTELogo1.png" and replace it with the existing file in the vendor/adminlte/dist/img/ folder of your project.
4: Reload your browser

<img width="277" alt="Captura de pantalla 2022-12-30 a la(s) 17 02 31" src="https://user-images.githubusercontent.com/119763858/210109920-9dbcd931-60b0-4684-b059-45327c9a6bad.png">
<img width="265" alt="Captura de pantalla 2022-12-30 a la(s) 17 02 54" src="https://user-images.githubusercontent.com/119763858/210109924-4856b389-8f69-4ac4-aed3-011fa5ab889d.png">

**Comment by dfsmania** [comment]
Are you making the changes inside `public/vendor/adminlte/dist/img` or in `vendor/almasaeed2010/adminlte/dist/img/`? Note the logo should be somewhere within the `public` folder.

Another reason may be because of the execution of `php artisan config:cache`, after that any configuration change won't have any impact. If that's your case, just run `php artisan config:clear` and be careful when using the cache commands on a development environment.

**Comment by marquezmiguel** [comment]
thank you very much for your answer, I was doing something wrong I was placing it in the directory: vendor/almasaeed2010/adminlte/dist/img/.
I have placed it in the directory: public/vendor/adminlte/dist/img and it works correctly.

I have a question about what is the directory: vendor/almasaeed2010/adminlte/dist/img/ used for?

**Comment by dfsmania** [comment]
All that is inside the `vendor` folder is a dependency of your `Laravel` application. This package requires the [ColorlibHQ/AdminLTE](https://github.com/ColorlibHQ/AdminLTE) package, and it is downloaded there when you execute `composer install` or `composer update`. Then, in the installation process of this package, some files are copied from the `AdminLTE` downloaded package to the public folder in order to use they.
