### ISSUE TITLE
[BUG] [QUESTION] progress bar greater than 100% not complete

### ISSUE THREAD

**Issue by billyboy35** [jeroennoten/Laravel-AdminLTE#1162]
### Describe the bug
if the value exceeds 100% the progress bar does not display anything, do you think this is normal operation, or am i doing something wrong ? (open question)

### Steps To Reproduce
1. use `<x-adminlte-progress theme="teal" value="2083.48" animated with-label/>`
2. See error
![image](https://user-images.githubusercontent.com/75578469/212427916-dc042439-8920-4101-b2da-fed77e62b6f2.png)

must be full :
![image](https://user-images.githubusercontent.com/75578469/212428436-4cf9d37b-7ee7-42fb-b298-2106f3fd3060.png)

### Environment
| Item    | Version
| ------- | -------
| Laravel | 9.0

### Additional context
to work around force the value to 100

```
@if($Task->progress() > 100 )
  <x-adminlte-progress theme="teal" value="100" animated/>
@else
  <x-adminlte-progress theme="teal" value="{{ $Task->progress() }}" animated/>
@endif
```

**Comment by dfsmania** [comment]
@billyboy35 I will check this out, maybe we can add some checks over the `value` attribute.

**Comment by billyboy35** [comment]
@dfsmania i can try to do this if you want

**Comment by dfsmania** [comment]
@billyboy35 sure, the change should be easy to implement, just add additional checks to the [Progress Component](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/src/View/Components/Widget/Progress.php) constructor. Actually, it just check that the value property is between `0` and `100`, otherwise it will be set as `0`. In the new version, we should check if the value is below to `0` or above to `100` to set it as `0` or `100` respectively...
