### ISSUE TITLE
How can I make the current menu item active?

### ISSUE THREAD

**Issue by WinsZP** [jeroennoten/Laravel-AdminLTE#1167]
Hello, I am using your Adminlte-Laravel package, which has vue 3 installed. How can I make the current menu item active through the adminlte.php file?

**Comment by dfsmania** [comment]
Maybe you are looking for next documentation:

[Menu Config - The Active Attribute](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-active-attribute)

**Comment by abdul-waheedHT** [comment]
I am using adminLTE (AR Language) and forgot to install it properly in Laravel from composer, I have just added the template and it is working fine. 
But problem is, I am retrieving the menu by looping through it dynamically by database table and now want to use active menu and its sub-menu but can't unable to do it. Kindly suggest some ideas.

**Comment by dfsmania** [comment]
@abdul-waheedHT Not sure what you have done, why not start a nice installation procedure again?

However, to make a menu item active you need to add the `active` class to the `a.nav-link` element that wraps it. For a sub-menu to be open, you need to add the `menu-open` class to the `li.nav-item` that wraps it. But, you will need to create some sort of logic to do all this job every time a new menu item is clicked, taking into account a previous clean of `active` and `menu-open` class before setting the new one.

All that job is automatically done by this package, so my suggestion is to start a new installation and migration of your project to that new installation. Otherwise you will be facing more issues on the future...

**Comment by dfsmania** [comment]
Closed, no more feedback...
