### ISSUE TITLE
[BUG] Error message Not showing in componet if return view()->withErrors(['field'=>'cutom message'])

### ISSUE THREAD

**Issue by fastered** [jeroennoten/Laravel-AdminLTE#1168]
Error message Not showing in component if return `view()->withErrors(['field'=>'cutom message'])`. However, on `redirect()`, `back()`, or after fail the validation works fine.

#### In controller:
```php
return view('pages.tel-numbers.answers.edit', [
    'title' => $title,
    'answer' =>$answer
])->withErrors(['voice' => 'Your custom message']);
```
 
#### In view:
 ```blade
<x-adminlte-input name="voice" label="voice'" placeholder="" data-mask
    enable-old-support value="{{$answer->voice}}">
    <x-slot name="prependSlot">
        <div class="input-group-text text-olive">
            <i class="fas fa-phone"></i>
        </div>
    </x-slot>
</x-adminlte-input>
```

if debug `$errors` in the view I can see the error, but in the component (`views\vendor\adminlte\components\form\input-group-component.blade.php`) the `$errors` is empty.

**Comment by dfsmania** [comment]
@fastered I played sometime with your example, it seems that when you use `withErrors()` method, it fails to share the `$errors` variable among all blade views (as it is done when you use a [validator](https://laravel.com/docs/9.x/validation#quick-displaying-the-validation-errors)) and this causes the bug, because `$errors` will be available on your `pages.tel-numbers.answers.edit` view, but not on the underlying component blade view. I will keep investigating if there is any solution for this...

**Comment by dfsmania** [comment]
@fastered After digging deeper I can clearly see that you are misusing the `withErrors()` method here. The one you are using is the available for the [\Illuminate\View\View](https://laravel.com/api/9.x/Illuminate/View/View.html#method_withErrors) which says:

![Screenshot 2023-02-07 at 14-26-26 Illuminate_View_View Laravel API](https://user-images.githubusercontent.com/63609705/217319414-e84ff114-89b6-48ea-b376-35ef26ec4d57.png)

So, it only adds the errors bag to the view instance you are referencing (i.e, not sharing with all views).

And the one that will work nicely is the available for [\Illuminate\Http\RedirectResponse](https://laravel.com/api/9.x/Illuminate/Http/RedirectResponse.html#method_withErrors) which says:

![Screenshot 2023-02-07 at 14-26-51 Illuminate_Http_RedirectResponse Laravel API](https://user-images.githubusercontent.com/63609705/217320566-b6df39e8-b78a-47ea-8a3e-d923ba5541c9.png)

So, instead of returning a **view with errors** you should try to rework your code to **redirect it to some route with the customized errors**.

**Comment by fastered** [comment]
Thank you very much, I thought about it, but with additional routes ... I did it differently, I made a check for an existing error so that the redirect is not infinite, and if there is an error in the session, then I return view ...
otherwise I check further, and if necessary, I redirect to the same route with errors

```
`  $view = view('pages.tel-numbers.answers.edit', [
            'title' => $title,         
            'answer' => $answer,          
        ]);

        if(Session::has('errors')) return $view;

        $text = $this->verify_exist_tel_voice($answer, 'tel_voice');

        if ($text) return redirect(route('tel.numbers.answer.edit',$number))->withErrors(['tel_voice' => $text]);    


        return $view;`
```
works good

**Comment by dfsmania** [comment]
Nice, can we close the issue?
