### ISSUE TITLE
[QUESTION] favorites in the menu

### ISSUE THREAD

**Issue by GuilhermeCamargoL** [jeroennoten/Laravel-AdminLTE#1169]
Is it possible to put favorites in the menu?

I wanna try something like this :
![image](https://user-images.githubusercontent.com/100958092/218121046-1f92ad8d-c8da-4243-adb8-c177c74f4ce0.png)

When I click on the star, it changes color and I save some information in the database to show a menu of favorites to the user. Like this:
![image](https://user-images.githubusercontent.com/100958092/218121588-ce99df8a-89fd-456b-b824-418e941d8f52.png)

In this example project, I'm using the adminLTE layout. But in the new project I'm building with this package, I can't add one more icon like this and make it have some interaction in the menu

Is there any way that can help me? Why didn't I find anything about :/

**Comment by dfsmania** [comment]
@GuilhermeCamargoL Sorry, there isn't anything built-in that support that particular feature. However, you may create a new fork of this package to add such feature. I suggest to look at next files:

- https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/partials/sidebar/menu-item-link.blade.php
- https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/partials/sidebar/menu-item.blade.php
- https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/src/Helpers/SidebarItemHelper.php

Using those files as a reference, you should try to integrate a new `menu-item-favorite-link` into the sidebar menu. Also, you would need to generate the menu at runtime, since you will check your database before creating it, for that look at:

- https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime

**Comment by GuilhermeCamargoL** [comment]
@dfsmania Thanks for the tips, I'll try to do my best so that I can do it, even though I'm just starting out in the world of programming, I'm having fun, anyway, thank you very much!
