### ISSUE TITLE
[HELP] JS files does not Work.

### ISSUE THREAD

**Issue by DiegoMaiaSSA** [jeroennoten/Laravel-AdminLTE#1191]
### Describe the bug
When i try to use JS files it doesn't work. If i try to call a js file like in documentation it don't work, as well as any js files.

### Steps To Reproduce
```blade
@section('js')
    <script> console.log('Hi!'); </script>
@stop
```

### Expected behavior
To execute js files or commands.

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | 10.x
| Project | 10.x
| OS      | Windows 11

### Additional context
I'm ussing laravel breeze, everything else is the normal package.

**Comment by dfsmania** [comment]
Hi @DiegoMaiaSSA , I suggest you first try to look up for errors on the browser dev console. Otherwise, it will be hard to track your problem.

Also, if you are trying to include some external `JS` file, the best way is to use it as a plugin, check [this documentation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration) if that's your case.

**Comment by DiegoMaiaSSA** [comment]
Thanks for helping! I find out what was the problem.
