### ISSUE TITLE
Custom-Made page.blade.php

### ISSUE THREAD

**Issue by HKGeeks** [JeroenNoten/Laravel-AdminLTE#12]
I found that I can duplicate the login.blade.php in views/vendor to loginadmin.blade.php and logincustomer.blade.php, and call it by using @extends('adminlte::pageadmin') and @extends('adminlte::pagecustomer'), but I want do the same thing with page.blade.php, it shows Undefined variable: adminlte, because I want to have different css color with different login role, how can I do that? Thank you!

**Comment by JeroenNoten** [comment]
Hey,

You better not duplicate, but double extend.

So in `pageadmin.blade.php` you write `@extends('adminlte::page')` And below, you write the customization for this page kind. So for example, you can override the `body_class` section in that file to change the skin color:

    @section('body_class', 'skin-green sidebar-mini')

Or if you need custom places to add styling, you can modify `admin.blade.php` to add extra `@yield()`s.

I recommend to place your added pages `pageadmin.blade.php` and `pagecustomer.blade.php` not in the `vendor` directory but for example in your own `layouts` directory. Then you can extend your added layout pages using `@extends('layouts.pageadmin')`.

Let me know if this answers your question.

**Comment by HKGeeks** [comment]
Thanks JeroenNoten, You helped me, Thanks!!

**Comment by paulheijman** [comment]
Hi Jeroen,
I'm still struggling with this, maybe you can help me...

I have the following structure:
```
views
├── layouts
│   ├── adminlte.blade.php
├── vendor
│   └── adminlte
│       ├── ...snip...
│       ├── master.blade.php
│       ├── page.blade.php
│       ├── ...snip...
└── welcome.blade.php
```
In welcome.blade.php I extend the `layouts\adminlte.blade.php` (which is basically page.blade.php with a few extra's).
`layouts\adminlte.blade.php` extends `adminlte::master`, but then I get an `Undefined variable: adminlte` because the View Composer only registers 'adminlte::page'...

What is the best way to customize the page without touching core plugin files?

Thanks in advance!

**Comment by jeroennoten** [comment]
Hi Paul!

Move your `views/layouts/adminlte.blade.php` to `views/vendor/adminlte/page.blade.php` (this will overwrite the existing `page.blade.php` file). And in `views/welcome.blade.php`, you extend `adminlte::page` instead of `layouts.adminlte`.

Note that the purpose of the `views/vendor` folder **is** to customize package's views. So this is the right thing to do.

**Comment by RSAAUTHENTICATIONPANKAJ** [comment]
i want that in multi authentication both admin and user have separate menu not the same menu
i have copied the code of page.blade.php and named it layouts\master.blade.php this newly create page is just for admin which is for the purpose of distinct side meu of admin from user but it is giving me error

Undefined variable: adminlte (View: C:\xampp\htdocs\singleauth\resources\views\layouts\master.blade.php) (View: C:\xampp\htdocs\singleauth\resources\views\layouts\master.blade.php)

when i remove this code
@each('adminlte::partials.menu-item', $adminlte->menu(), 'item')
from

        </ul>

then it don,t give me error but it does not show me any thing

i just want differnt side menu link of admin from user i want to customize the side menu for admin and want to use the defalut side menu for user     .  I do not understand where  $adminlte is defined.  how can I do that? Thank you!

**Comment by tantana5** [comment]
You can run:
php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views
And you can edit in "resources/views/vendor/adminlte"
