### ISSUE TITLE
[BUG] iFrame Mode functionality generates a bug with Livewire (v3)

### ISSUE THREAD

**Issue by eduardo-de-carvalho-couto** [jeroennoten/Laravel-AdminLTE#1222]
Using iFrame mode, when I navigate from one page to another, the previous page remains.

![Captura de tela de 2023-09-27 13-44-56](https://github.com/jeroennoten/Laravel-AdminLTE/assets/101133249/d0608bf6-0fff-40e3-b4b2-1bda2eb33279)
![Captura de tela de 2023-09-27 13-43-22](https://github.com/jeroennoten/Laravel-AdminLTE/assets/101133249/04dc9b9d-5b94-449d-b77d-76dea5fedfdb)
![Captura de tela de 2023-09-27 13-43-30](https://github.com/jeroennoten/Laravel-AdminLTE/assets/101133249/ed6dc67e-910b-4d51-837a-542b79c8e68e)

Ps.: I'm using Filamentphp v3(TALL STACK).

I greatly appreciate everyone!

| Item    | Version
| ------- | -------
| Laravel | 10

**Comment by dfsmania** [comment]
Hi @eduardo-de-carvalho-couto I doubt we can fix anything from here since `iFrame` mode is implemented on the underlying `AdminLTE` package, from this package it's just used as provided by the `AdminLTE` package, . On the other side, you are mixing it with `Livewire` and `Filament` and maybe it's a compatibility problem with they. If you can track an error on the browser's console, I suggest you to open a detailed issue on the `AdminLTE` package. Maybe you can get some help from the community there...

**Comment by EugenVarz** [comment]
Hi all
Unfortunately, the error is also present in pure AdminLTE/Laravel in iframe mode. Conflicts with other packages are not confirmed

**Comment by SMEWebify** [comment]
Hi @EugenVarz 

Is this a livewire update that you carried out?

migrating from v2 to 3 is really not easy.

for me the Iframe mode works with livewire 3

Regards

Kévin

**Comment by dfsmania** [comment]
Closed, seems to be a problem of integration with other frameworks. If anyone finds this same error on a standalone `Laravel-AdminLTE` package please reopen with the details to reproduce the problem.
