### ISSUE TITLE
Do not introduce disruptive updates in minor version 

### ISSUE THREAD

**Issue by SimoneOpenapi** [jeroennoten/Laravel-AdminLTE#1256]
My composer.json file was:

"jeroennoten/laravel-adminlte": "^3.9"

This was automatically configured when I installed the "jeroennoten/laravel-adminlte" package.

When I pushed a change, my pipeline ran "composer update" and my web application broke.

If possible, it would be helpful to avoid non-backward compatible changes in minor versions to prevent this type of behavior.

I have now pinned the version to 3.9.4 while I wait to test the new version. This is probably due to a suboptimal habit of mine, but this normally does not happen with other packages in my projects. If you have any suggestions on how to improve my pipeline, I would be happy to hear them.

**Comment by dfsmania** [comment]
Hi @SimoneOpenapi, can you please share what error are you experiencing?

Also, have you published the package views? If that's the case, you'll need to update them to work nicely with the new `v3.9.5`, check [Updating](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating).

In a production environment, you are not supposed to apply composer update since it can be risky. Instead, in my opinion, I think it's better to apply these updates in a development scenario and keep the `composer.lock` file versioned on safety points, then in production you deploy safety versions of your Laravel application, and execute `composer install` instead.

**Comment by SimoneOpenapi** [comment]
Hi @dfsmania 
Thank you for your attention and suggestions, I will treasure them.
Here is the error:

`production.ERROR: Call to undefined method JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper::isPreloaderEnabled() (View: /var/www/html/resources/views/vendor/adminlte/page.blade.php)`

I hadn't really noticed the new version and the update was actually quick.
I have now solved everything and I am using 3.9.5.

P.S. Thank you again for the work you do on this useful project.

**Comment by dfsmania** [comment]
OK, good to know you've solved it. The update broke your app because you've published the package views previously, so the published views were out-of-date. Remember to always follow the update procedure explained in the Wiki when updating this package.

Regards!
