### ISSUE TITLE
[FEATURE] Bootstrap version update

### ISSUE THREAD

**Issue by guga121** [jeroennoten/Laravel-AdminLTE#1286]
### Is your request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when...
Hello again dfsmania,

There is a way to update bootstrap version to the latest one?

thanks in advance.

### Describe the solution you'd like
A clear and concise description of what you want to happen or the enhancement you want.

**Comment by dfsmania** [comment]
Hi @guga121 , unfortunately Bootstrap version is bound to the underlying **AdminLTE** package. So there is no way to update it independently. There's currently a new beta version of **AdminLTE (v4)** that was created from scratch with **Bootstrap 5**, but as is was made from scratch it completely differs from the one we are using here (**v3**) and has a lot of missing features (currently). So, integrating it here will require a lot of work and time that I don't have currently. So, by the moment, there's no plan for this update.

Check more details at next issue:

https://github.com/jeroennoten/Laravel-AdminLTE/issues/1278

**Comment by gpibarra** [comment]
There is already a beta2 of adminlte4. I have been doing some tests, although the `dist` folder resulting from the build is not committed in the repository, I used the `https://adminlte-v4.netlify.app/dist` page to link the css/js files. I was also able to compile it with vite.

I have started to change the auth views and also the page and master views, but it is still very early work.
As you said, the adminlte package has many changes that will impact this package, and I thought that if in the future this package supports adminlte it should be done in a new branch since it will not be compatible (although someone can also argue if it is convenient to make a new package, my opinion is that it would be better to use this same package in a new v4.x branch since it would have more reach to users than if a new package were created).

In case you decide to create a new branch, I think that the approach of having the documentation in a wiki is not that flexible to offer the documentation of 2 versions that have differences in configuration or features. I saw that a long time ago the documentation was in the `Readme.md` and everything was moved to the wiki (https://github.com/jeroennoten/Laravel-AdminLTE/pull/720), wouldn't it be better to use vitepress and use github pages to have the documentation, and in the future would it be better to have both versions active on the site? What do you think? I think I could make a PR with that configuration.

On the other hand, in view of a possible new adminlte branch, do you think that the minimum requirements should be laravel10 php8.1 and node 18 with vite?

**Comment by dfsmania** [comment]
@gpibarra Thanks for sharing your ideas, I would really like having the documentation in a github page, I was looking for this some time ago but I gave it up because lack of free time. Currently, there are a lot of notes about versions in the Wiki pages and having a versioned documentation will really help on this.

About **AdminLTE v4**, it's too inactive right now. I really don't know if there will ever be a release version with all the features **AdminLTE v3** has currently. Also and not less important, currently I don't have the time to implement a branch for support **AdminLTE v4**. But you are free to go in your own fork, and if you go to a stable point, maybe we can share a link from here.

Sorry not to compromise with this as you will like, but my free time can only afford a maintenance over this package right now.

**Comment by gpibarra** [comment]
brilliant! I'm also using some free time, the migration to v4 is going to be difficult, and they released quite a few things I've been seeing

On the other hand, if you want, I can do a PR with the Vitepress configuration, although I couldn't extract everything from the wiki because it would be nice to have the original markdown that is accessed when you are a collaborator. then I would upload the configuration and you would update the md files and configure the tokens for the deploy in github pages

**Comment by dfsmania** [comment]
@gpibarra I think you can clone the Wiki locally to access the original markdown, see [this](https://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki). As for the package I do have collaborator access only (not admin), so I can only do a limited numbers of things on it. But I will try to help on this if you create a PR for it...

**Comment by gpibarra** [comment]
I had checked that when forking the wiki section was not copied, in my newly forked repo the wiki is empty.

However, I have seen that you can directly clone the wiki with the command `git clone https://github.com/jeroennoten/Laravel-AdminLTE.wiki.git`. With that I was able to correctly access the original markdown. I just uploaded the PR, we are still there.
