### ISSUE TITLE
Where is the Kernel.php file?  I do not have It in the  app/Http/Middleware folder

### ISSUE THREAD

**Issue by Ubenga** [jeroennoten/Laravel-AdminLTE#1307]
| Question          | Answer
| ----------------- | -----------------------
| Issue Type        | QUESTION
| Laravel Version   | 11
| Project Version   | Laravel 11 whit Admilte

**Comment by Ubenga** [comment]
Where is the Kernel.php file? I do not have It in the app/Http/Middleware folder

**Comment by dfsmania** [comment]
@Ubenga Please, only open issues related to this package here, your problem is more related to Laravel 11. Do a search on the internet, since in Laravel 11 the app structure was minimized, see [Laravel 11 - Release Notes](https://laravel.com/docs/11.x/releases#laravel-11). For your particular question, read next:

https://stackoverflow.com/questions/78532447/laravel-kernel-php-file-alternative
