### ISSUE TITLE
How to change the menu file path 

### ISSUE THREAD

**Issue by rambo666** [jeroennoten/Laravel-AdminLTE#1309]
### Is your request related to a problem? Please describe.
How to change the file path for menus links? I want a seperate file location in config for changing menu arrays. 

### Describe the solution you'd like
Please allow the adminLTE config file to locate menu files. 

### Describe alternatives you've considered
I would also like something like multiple menus for multiple purposes

### Additional context
The only way to change the location of the menu array is to directly update the vendor file which is not viable. I want a feature where I can dynamically locate the menu file from config folder. For example I have menus.php in config folder I want to use that file instead of adminlte config file by default.

**Comment by dfsmania** [comment]
Hello @rambo666 , to split menu configuration into a different file you may use next approach.

In the `adminlte.php` config file, use next definition instead of defining the menu array explicitly there:

```php
menu => include 'adminlte_menu.php',
```

Then you can split the menu configuration into the file `adminlte_menu.php` that should also be located into the `config` folder of your Laravel project. For example:

#### `config/adminlte_menu.php`
```php
<?php

return [
    // Define all your menu entries here.
];
```

You may use this same approach to have multiple menu files, example:

#### `config/adminlte_menu.php`
```php
<?php

if (/* condition 1*/) {
    return include 'menus/adminlte_menu1.php';
} elseif (/*condition 2*/) {
    return include 'menus/adminlte_menu2.php';
} else {
    return include 'menus/adminlte_default_menu.php';
}
```

I'm not really sure what your goals are, but you can also take a look to [Dynamic Menu Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#dynamic-menu-config) and create your menu dynamically (maybe by getting the menu entries from a database).

**Comment by rambo666** [comment]
This is exactly I am looking for. I knew to use include in the adminLTE for menus. But i was hoping that if there was a way to include files directly from different config file. For example, a condition in adminLTE config file as useSeperateMenuFile=bool. IF useSeperateMenuFile=true, specify the menu path in adminLte config file otherwise use default menu from the config.

**Comment by dfsmania** [comment]
@rambo666 I don't see a real benefit from having those new configurations available, other than it will make explicitly something that can already be done with `PHP`. I will re-think this in the future, just in case, but I don't want to make the config file any larger now, it already include too many options. Anyway, thanks for your suggestion!
