### ISSUE TITLE
[QUESTION] LivewireAlert integration

### ISSUE THREAD

**Issue by djgraphics28** [jeroennoten/Laravel-AdminLTE#1323]
How can I implement LivewireAlert Package for this?

**Comment by dfsmania** [comment]
@djgraphics28 Do you want to use [jantinnerezo/livewire-alert](https://github.com/jantinnerezo/livewire-alert) in conjunction with this package?

**Comment by dfsmania** [comment]
@djgraphics28 I just tested the package I mentioned previously on a local environment. Hopefully, is the one you asked for. Use next integration steps as a reference (assuming you have **Livewire already installed**):

### 1. Install Livewire-Alert with composer

```sh
composer require jantinnerezo/livewire-alert
```

### 2. Enable Livewire on configuration file
Open the `config/adminlte.php` file of your project, locate the **livewire section** in the config file and be sure enable it:

```php
/*
|--------------------------------------------------------------------------
| Livewire
|--------------------------------------------------------------------------
|
| Here we can enable the Livewire support.
|
| For detailed instructions you can look the livewire here:
| https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Other-Configuration
|
*/

'livewire' => true,
```

### 3. Ensure SweetAlert2 plugin is configured
Open the `config/adminlte.php` file of your project, locate the **plugins section** in the config file and be sure next entry exists:

```php
'plugins' => [
    .
    .
    .
    'Sweetalert2' => [
        'active' => true,
        'files' => [
            [
                'type' => 'js',
                'asset' => true,
                'location' => 'vendor/sweetalert2/sweetalert2.min.js',
            ],
            [
                'type' => 'css',
                'asset' => true,
                'location' => 'vendor/sweetalert2/sweetalert2.min.css',
            ],
        ],
    ],
    .
    .
    .
],
```

This setup uses `SweetAlert2` from local drive, which needs to be previously installed on `public/vendor` by executing:

```sh
php artisan adminlte:plugins install --plugin=sweetalert2
```
Alternatively, you can use **CDN files** on the configuration entry if you like, in that case `'asset' => false` should be used.

For more details about this check [Plugins Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration).

### 4. Add Livewire-Alert scripts on your app layout

If you followed the [Recommended Way of Use](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Usage#recommended-way-of-use) for this package, then just add next lines at the end of your app layout:

```blade
{{-- Include livewire-alert scripts. --}}

@push('js')
    <x-livewire-alert::scripts />
@endpush
```

Otherwise, you'll need to include those lines on all blade files extending the main layout provided by this package, that will used the alerts.

### 5. Use Livewire-Alert package on the backend

As explained on that package documentation, you are now able to use its tools to show an alert from the backend, but I think it can only be used on **Livewire components**, I couldn't make it work on a basic Laravel controller. So, I tested it on a basic Livewire component that is used as example on most situations, see next for reference:

#### app/Http/Livewire/Counter.php
```php
<?php

namespace App\Http\Livewire;

use Jantinnerezo\LivewireAlert\LivewireAlert;
use Livewire\Component;

class Counter extends Component
{
    use LivewireAlert;

    /**
     * The query string, useful to keep state when iterating over the browser's
     * history.
     */
    protected $queryString = [
        'count' => ['except' => 0, 'as' => 'c'],
    ];

    public $count = 0;

    public function increment()
    {
        $this->count++;
        $this->alert('info', "Counter is now: {$this->count}");
    }

    public function decrement()
    {
        $this->count--;
        $this->alert('info', "Counter is now: {$this->count}");
    }

    public function render()
    {
        return view('livewire.counter');
    }
}
```

#### resources/views/livewire/counter.blade.php
```blade
<div style="text-align: center">

    <x-adminlte-button wire:click="increment" icon="fas fa-lg fa-plus"/>
    <x-adminlte-button wire:click="decrement" icon="fas fa-lg fa-minus"/>

    <h1>{{ $count }}</h1>

</div>
```

Then, use that Livewire component anywhere in your project to test the alerts:

```blade
<livewire:counter/>
```

**Comment by djgraphics28** [comment]
Thanks it worked, how about implementing Toastr?

**Comment by dfsmania** [comment]
@djgraphics28 Please add a link to the **Toastr package**...

**Comment by djgraphics28** [comment]
how can I use it it my livewire?

**Comment by dfsmania** [comment]
Sorry, I can't help you if you don't give any details. Integrations with other packages should be first tried by yourself, use the previous example I give as reference, read documentation, search around the closed issues, etc. So, when you get into a specific and concrete problem, you can share details here and ask for help to the community.
