### ISSUE TITLE
Error 403 - Dark Mode 

### ISSUE THREAD

**Issue by vls2021** [jeroennoten/Laravel-AdminLTE#1326]
### Describe the bug
Dark Mode in AdminLte 3 is returning error 403. Permissions are correct. I've already reviewed the code, and everything is normal.

### Steps To Reproduce
1. Go to 'Google Chrome F12 '
2. Click on 'Console '
3. Select 'Log XmlHttpRequests'

### Expected behavior
When I select the icon to activate Dark Mode, the error reported occurs. Some computers work in Dark mode, and save the data in the Database, but in others, it gives a 403 error and does not save the user's option to have or without Dark mode.

### Screenshots
![tela2](https://github.com/user-attachments/assets/a1be057c-70a2-482a-830d-e14f85c4d013)

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | 8
| Project | Adminlte 3
| OS      |  Linux Amazon EC2 

### Additional context
Please, help-me. :-)

**Comment by dfsmania** [comment]
@vls2021 Could you add more detailed info about the error displayed when making the POST to the `adminlte/darkmode/toggle' route. You can inspect it on the **Network** tab too.

Also:

1. What version of this package are you using currently?
2. Execute `php artisan route:list` and check if the darkmode routes are registered in that list.

**Comment by vls2021** [comment]
What version of this package are you using currently? 
R: Version 3.9
Execute php artisan route:list and check if the darkmode routes are registered in that list.
R: 
![lists](https://github.com/user-attachments/assets/dbb40dea-71d1-4084-9609-bf11a0159725)

**Comment by dfsmania** [comment]
What about detailed information of the POST to `adminlte/darkmode/toggle` route?

**Comment by vls2021** [comment]
Error 403 appears on this computer. Every time I have to change the dark or light mode, the error occurs in this part of the code.

See:

![img403](https://github.com/user-attachments/assets/26cb9d8e-f091-4f06-aa4e-3b638eb370dc)

![img403-2](https://github.com/user-attachments/assets/609f3cf7-09f6-402d-92d0-c113c2c6d0c6)

![img403](https://github.com/user-attachments/assets/3adfcccd-8b6c-4d59-a4b3-5065ad2559eb)

**Comment by dfsmania** [comment]
For what I can see, you're hardcoding the  `X-CSRF-TOKEN` and that's a mistake. Laravel's generates a CSRF token for each active session (and they expire when the session ends), so you can't use a hardcoded value, that's why you get **403 Forbidden**. Replace your fetch configuration by something like next:

```js
const fetchCfg = {
    headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}' },
    method: 'POST',
};
```

Read more about this on: https://laravel.com/docs/csrf

**Comment by dfsmania** [comment]
OK, I see, your previous mage was part of a debug procedure then?

So, if I understood correctly, the Laravel app you created works on some devices and do not work on other devices?

**Comment by vls2021** [comment]
Correct. I will check if there is any notification in the log.

**Comment by vls2021** [comment]
logs have no errors

:-(

**Comment by dfsmania** [comment]
You'll need to track down in the server code in what point that 403 response is generated. You can also try to add a logging middleware to grab more information from each request-response cycle: https://medium.com/@mehhfooz/log-requests-and-responses-in-laravel-f859d1f47b74

It's hard to know how to proceed otherwise...

**Comment by vls2021** [comment]
I'll check. About how it works, it is as follows: The application is hosted on Amazon EC2. In my work the error appears in the debug, but dark mode works. When I do the test at home, or in another location outside of where I work, the error occurs but the operation does not complete, and 0 403 appears. It's a big mystery.

**Comment by dfsmania** [comment]
OK, what's that error your are experiencing when the dark mode works?

I'm not sure why the request is rejected by **403 Forbidden**, I don't think the related controller method is even hit. Maybe some middleware of the "web" group is rejecting the request, or a firewall in the server, and we need to know why first...

You may add some logs at `vendor/jeroennoten/laravel-adminlte/src/Http/Controllers/DarkModeController.php` to check if the methods are hit, but it seems the request is rejected before reaching the controller.

**Comment by vls2021** [comment]
I suspect there is a problem with the session. It is returning in: return session($this->sessionKey); in DarkModeController.php in the IsEnabled function

![session](https://github.com/user-attachments/assets/9d6d358f-573d-4645-ab76-134e81780d95)

**Comment by dfsmania** [comment]
@vls2021 Why would that be an error? That logic inspects if dark mode state is stored in the current user session and uses that value to check whether it's enabled or not. Otherwise it will fallback to the package configuration value (the default one by config). Returning there doesn't mean anything wrong, unless you are experiencing some sort of exception.

**Comment by dfsmania** [comment]
@vls2021 did you found a solution to this issue?

**Comment by dfsmania** [comment]
Closed, no more feedback, it seems to be a deployment issue...
