### ISSUE TITLE
[QUESTION] How to use fortify with this project?

### ISSUE THREAD

**Issue by matteobortolini01** [jeroennoten/Laravel-AdminLTE#1328]
How can I replace the "laravel/ui" package built into AdminLTE with fortify without any conflicts?

**Comment by dfsmania** [comment]
I didn't try this, but use as a start guide:
1. Don't  install `laravel/ui`.
2. [Plublish the package view](https://jeroennoten.github.io/Laravel-AdminLTE/sections/configuration/views_customization.html)
3. Customize the authentication views so they interact with fortify backend.

**Comment by matteobortolini01** [comment]
I have already installed laravel/ui and unfortunately I can't trash the whole project.
Is there a way to avoid having to delete everything and have to start all over again?
I already have everything set up, I just need to figure out how to replace laravel/ui with fortify.

Thanks for the reply.

**Comment by dfsmania** [comment]
I don't think you'll need to start your project again, just work on all the authentication logic to communicate with `fortify` instead of `laravel/ui`. Then you can uninstall `laravel/ui`. Unfortunately, I don't have a guide for this because I never tried `fortify` (still). You won't evade steps 2 and 3 explained before, customization of the authentications views will be required for your goals.

**Comment by matteobortolini01** [comment]
Thanks for helping.
