### ISSUE TITLE
UrlGenerator is not instantiable

### ISSUE THREAD

**Issue by niciz** [jeroennoten/Laravel-AdminLTE#199]
I tried to implement this module in my **LUMEN** app following your installation guide but it fails on directive @extends('adminlte::page') with this error:

ErrorException
Target [Illuminate\Contracts\Routing\UrlGenerator] is not instantiable. (View: /<path_to_my_app>/vendor/jeroennoten/laravel-adminlte/resources/views/page.blade.php) (View: /<path_to_my_app>/vendor/jeroennoten/laravel-adminlte/resources/views/page.blade.php)

How can I solve this? I know that this is for laravel but maybe you know something that could help me..

**Comment by loekiedepo** [comment]
This is due to you using Lumen. Lumen simply doesn't have the features of Laravel, some of which this package depends on.
You can try to hack around a little though, since there is a [UrlGenerator](https://github.com/laravel/lumen-framework/tree/5.6/src/Routing) in Lumen; it's just in another namespace.

However, as Lumen is marketed as a stateless API framework, I'd recommend just using Laravel as you're bound to run into error after error.
