### ISSUE TITLE
Add Buttons on top Nav

### ISSUE THREAD

**Issue by carlosencinesw** [jeroennoten/Laravel-AdminLTE#203]
Hi

How i add buttons on top-nav 

![whatsapp image 2018-04-27 at 08 58 39](https://user-images.githubusercontent.com/26942282/39363178-bd9d37ee-49ff-11e8-9e53-2e66d0349d6d.jpeg)

I thank you for your attention

**Comment by okielah** [comment]
Edit the view file: vendor\adminlte\page.blade.php
Put it under the comment
`<!-- Navbar Right Menu -->`

**Comment by mrtass** [comment]
hi 
@okielah this page doesn't exist 
@carlosencinesw did u get it to work ?

**Comment by valdineifer** [comment]
I'm also trying to do this. Did someone found the solution?
I didn't found any file with this name, @okielah. (I use the VS Code search tool too: no results)

**Comment by mhajder** [comment]
I see that the issue is still not closed.
If you want to edit the views, just use the `php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views` command. 

Documentation: https://github.com/jeroennoten/Laravel-AdminLTE#7-customize-views

Views for editing appear in `resources/views/vendor/adminlte`.

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.

**Comment by luisangelMV** [comment]
you can simply use 
`@section('content_top_nav_right')
@parent
<button class="btn btn-outline-secondary" type="submit">{{ $textButton }}</button>
@endsection`
