### ISSUE TITLE
How to use css which complied by laravel-mix

### ISSUE THREAD

**Issue by DivingPigy** [jeroennoten/Laravel-AdminLTE#302]
Hi!
I am going to use css which compiled by laravel-mix. However, it seems some css conflicts caused by 
`<link rel="stylesheet" href="{{asset('css/app.css')}}">`
![image](https://user-images.githubusercontent.com/26334368/58064044-40eac180-7bb3-11e9-8420-b7f7d7390517.png)
conflict as the picture above shows, menu bar wrong positon

Any solution to solve this conflict? Thank you!

**Comment by DivingPigy** [comment]
![image](https://user-images.githubusercontent.com/26334368/58064159-a048d180-7bb3-11e9-91fe-d92b2a812afc.png)

**Comment by dmotors** [comment]
Same issue here. If I include the css/app.css there seems to be some conflict.

If I comment out this line from resources/sass/app.scss then it seems to be fine:

```
// Bootstrap
//@import '~bootstrap/scss/bootstrap';
```

However I'm not sure if it's because this package is using an older version of bootstrap or if there is more deeper css conflicts going on with Laravel's default setup. Would prefer not to disable that line if don't have to.

**Comment by DivingPigy** [comment]
@dmotors You are right. We can remove 
`//@import '~bootstrap/scss/bootstrap';`

Then, import other css. Use plugin via js.
