### ISSUE TITLE
It's possible to generate all views of AdminLTE 3?

### ISSUE THREAD

**Issue by mvnp** [jeroennoten/Laravel-AdminLTE#455]
It's possible to generate all views of AdminLTE 3 admin template or just home.blade.php?

**Comment by lacodimizer** [comment]
@REJack over a demo install command?

**Comment by REJack** [comment]
If he mean the demo home blade file, this can be installed with the only switch.

**Comment by pardoxp** [comment]
I had same question here because I remember the version 2 when you ran adminlte:install the default views were overwritten and now they don't, and the other thing I've noticed is that in the login view for example we have this
`@section('adminlte_css_pre')
    <link rel="stylesheet" href="{{ asset('vendor/icheck-bootstrap/icheck-bootstrap.min.css') }}">
@stop`
and this file doesn't exist actually, so do we have to install this plugin manually???

**Comment by REJack** [comment]
Yep the plugin need to be installed seperatly with `adminlte:plugins`, you can check the readme to get more details about the command.
