### ISSUE TITLE
Add meta content for CSRF token

### ISSUE THREAD

**Issue by Basili0** [jeroennoten/Laravel-AdminLTE#46]
Could you please add `<meta name="csrf-token" content="{{ csrf_token() }}">` to the master.blade.php?

**Comment by loekiedepo** [comment]
What's the use of this? Laravel [automatically](https://laravel.com/docs/5.3/csrf#csrf-introduction) inserts csrf token into your user's session, and you only really need them on form pages, as described in the docs too.

Using [LaravelCollective Form library](https://laravelcollective.com/docs/5.3/html#opening-a-form) even does adding tokens on forms automatically.

**Comment by Basili0** [comment]
Laravel also checks for CSRF tokens on ajax requests. And if you have no forms on the page, the only way to pass the token to the script is via <meta> tag.

**Comment by loekiedepo** [comment]
Aah okay, didn't know that.

**Comment by jeroennoten** [comment]
A meta tag is only one way to achieve this. I do not want to force one way by adding this tag to the template.

You can easily add this to the template yourself by creating a new blade template with the following contents: 

```
@extends('adminlte::page')

@section('css')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop
```

Save this for example as `resources/views/layouts/app.blade.php` and then use `@extends('layouts.app')` instead of `@extends('adminlte::page')`

**Comment by inbaz** [comment]
We're using this one to be able to have multiple css sections:

```
@extends('adminlte::page')

@push('css')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@endpush
```
