### ISSUE TITLE
Different menus per route group

### ISSUE THREAD

**Issue by 11digitlabs** [JeroenNoten/Laravel-AdminLTE#5]
I was wondering, is there a more elegant way that we can set different menus based on route.
For example the `admin` group in the routes.php to have menu A and the `user` group to have menu B

Right now, what I've done is setting an empty menu in the `config/adminlte.php` and then in the routes.php, i'm creating the menu per group, 

```php
Route::group(['prefix' => 'admin'], function () {
	Route::get('dashboard', function () {

		Event::listen('JeroenNoten\LaravelAdminLte\Events\BuildingMenu', function ($event) {
			$event->menu->add('MAIN NAVIGATION');
			$event->menu->add([
				'text' => 'Blog',
				'url'  => 'admin/blog',
			]);
		});

		return view('welcome');
	});
});

```

Sorry for all these questions, but I think that you have been through these issues before me, and it would be a pitty to recreate the wheel

**Comment by JeroenNoten** [comment]
You could solve this for example with a route group middleware. Run `artisan make:middleware AdminMenu` and `artisan make:middleware UserMenu`. You can find the created middleware in the `app/Http/Middleware` directory. Add the menu configuration code above `return $next($request);` in the middleware. In `app/Http/Kernel.php`, add `'menu.admin' => AdminMenu::class` and `'menu.user' => UserMenu::class` to the `$routeMiddleware` array (don't forget to import the classes at the top). Then in your `routes.php`:

```
Route::group(['prefix' => 'admin', 'middleware' => 'menu.admin'], function () {
    Route::get('dashboard', function () {
        return view('welcome');
    });
});

Route::group(['prefix' => 'user', 'middleware' => 'menu.user'], function () {
    Route::get('dashboard', function () {
        return view('welcome');
    });
});
```

Alternatively, you could use just one middleware with parameters if that is more convenient (for example if you have menu items that both groups need).

**Comment by dinarrhamiya** [comment]
may I see your config/adminlte.php for the menu ??

**Comment by haqktd** [comment]
how can I use route instead of url in menu configuration

**Comment by collinsNick** [comment]
Based on the answers provided above this is how i implemented mine,

1. Cleared the adminlte.php menu because both groups will see different menus

![001_admin_lte](https://user-images.githubusercontent.com/20722002/71308321-0167aa80-240c-11ea-8720-8d9680d6ead2.PNG)

2.created to files in the config directory to hold individual group route arrays

![002_config_files](https://user-images.githubusercontent.com/20722002/71308397-290b4280-240d-11ea-8138-6899663459af.PNG)

3. The administration routes in the administration.php
![003_admin](https://user-images.githubusercontent.com/20722002/71308338-51467180-240c-11ea-84cc-bbd1da07c3a4.PNG)

and the other one
![004_self_service](https://user-images.githubusercontent.com/20722002/71308344-5b687000-240c-11ea-8980-1fe19e542c16.PNG)

4. I then created a middleware that accepts a menu type paramenter and used that to determine the route arrays to render

![middlware](https://user-images.githubusercontent.com/20722002/71308354-8f439580-240c-11ea-9742-6b410e5cc049.PNG)

5. Added middleware to my route group routes

![middlware](https://user-images.githubusercontent.com/20722002/71308358-a3879280-240c-11ea-8422-0acba7a1fb59.PNG)

6. this renders different menu for the different route groups

Administration
![administration_menu](https://user-images.githubusercontent.com/20722002/71308362-bef29d80-240c-11ea-9ba0-b3c5c1d0c7d4.PNG)

Self Service

![self_service_menu](https://user-images.githubusercontent.com/20722002/71308371-d3369a80-240c-11ea-8d57-8c7a57fe77bb.PNG)

You can aslo add permissions to the menu items,Hope this helps somebody, Any suggestions are welcomed

**Comment by LasanthaSudeera** [comment]
> Based on the answers provided above this is how i implemented mine,
> 
> 1. Cleared the adminlte.php menu because both groups will see different menus
> 
> ![001_admin_lte](https://user-images.githubusercontent.com/20722002/71308321-0167aa80-240c-11ea-8720-8d9680d6ead2.PNG)
> 
> 2.created to files in the config directory to hold individual group route arrays
> 
> ![002_config_files](https://user-images.githubusercontent.com/20722002/71308397-290b4280-240d-11ea-8138-6899663459af.PNG)
> 
> 1. The administration routes in the administration.php
>    ![003_admin](https://user-images.githubusercontent.com/20722002/71308338-51467180-240c-11ea-84cc-bbd1da07c3a4.PNG)
> 
> and the other one
> ![004_self_service](https://user-images.githubusercontent.com/20722002/71308344-5b687000-240c-11ea-8980-1fe19e542c16.PNG)
> 
> 1. I then created a middleware that accepts a menu type paramenter and used that to determine the route arrays to render
> 
> ![middlware](https://user-images.githubusercontent.com/20722002/71308354-8f439580-240c-11ea-9742-6b410e5cc049.PNG)
> 
> 1. Added the middleware to my route group routes
> 
> ![005_web_routes_with_middleware](https://user-images.githubusercontent.com/20722002/71308442-aafb6b80-240d-11ea-9714-89e3197b058c.PNG)
> 
> 1. this renders different menu for the different route groups
> 
> Administration
> ![administration_menu](https://user-images.githubusercontent.com/20722002/71308362-bef29d80-240c-11ea-9ba0-b3c5c1d0c7d4.PNG)
> 
> Self Service
> 
> ![self_service_menu](https://user-images.githubusercontent.com/20722002/71308371-d3369a80-240c-11ea-8d57-8c7a57fe77bb.PNG)
> 
> You can aslo add permissions to the menu items,Hope this helps somebody, Any suggestions are welcomed

Thank you very much. You saved my day.

**Comment by collinsNick** [comment]
> > Based on the answers provided above this is how i implemented mine,
> > 
> > 1. Cleared the adminlte.php menu because both groups will see different menus
> > 
> > ![001_admin_lte](https://user-images.githubusercontent.com/20722002/71308321-0167aa80-240c-11ea-8720-8d9680d6ead2.PNG)
> > 2.created to files in the config directory to hold individual group route arrays
> > ![002_config_files](https://user-images.githubusercontent.com/20722002/71308397-290b4280-240d-11ea-8138-6899663459af.PNG)
> > 
> > 1. The administration routes in the administration.php
> >    ![003_admin](https://user-images.githubusercontent.com/20722002/71308338-51467180-240c-11ea-84cc-bbd1da07c3a4.PNG)
> > 
> > and the other one
> > ![004_self_service](https://user-images.githubusercontent.com/20722002/71308344-5b687000-240c-11ea-8980-1fe19e542c16.PNG)
> > 
> > 1. I then created a middleware that accepts a menu type paramenter and used that to determine the route arrays to render
> > 
> > ![middlware](https://user-images.githubusercontent.com/20722002/71308354-8f439580-240c-11ea-9742-6b410e5cc049.PNG)
> > 
> > 1. Added the middleware to my route group routes
> > 
> > ![005_web_routes_with_middleware](https://user-images.githubusercontent.com/20722002/71308442-aafb6b80-240d-11ea-9714-89e3197b058c.PNG)
> > 
> > 1. this renders different menu for the different route groups
> > 
> > Administration
> > ![administration_menu](https://user-images.githubusercontent.com/20722002/71308362-bef29d80-240c-11ea-9ba0-b3c5c1d0c7d4.PNG)
> > Self Service
> > ![self_service_menu](https://user-images.githubusercontent.com/20722002/71308371-d3369a80-240c-11ea-8d57-8c7a57fe77bb.PNG)
> > You can aslo add permissions to the menu items,Hope this helps somebody, Any suggestions are welcomed
> 
> Thank you very much. You saved my day.

you are most welcome, glad it helped

**Comment by rugggarr** [comment]
Excellent solution my friend! but... I keep getting : Class 'App\Http\Middleware\Event' not found 

Any clue?

**Comment by collinsNick** [comment]
> Excellent solution my friend! but... I keep getting : Class 'App\Http\Middleware\Event' not found
> 
> Any clue?

sorry to here that, These are the classes i included at the top of the file, I am guessing you need the last one 
(use Illuminate\Support\Facades\Event;). Try importing it.

use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;
use Closure;
use Illuminate\Support\Facades\Event;
