### ISSUE TITLE
Multi Lebel menu does not work properly. I can't expand the menu to access the submenu.

### ISSUE THREAD

**Issue by takielias** [jeroennoten/Laravel-AdminLTE#656]
Issue or Enhancement    | Issue
 Laravel Version         | 6.18
 Project Version         | 3.4.1

### Current Behavior

Multi Lebel menu does not work properly. I can't expand the menu that is why I can't access the submenu.

### Expected Behavior

Expand the menu and the submenu should be clickable.

### Steps to Reproduce

I just upgrade to 3.4.1 and Comment out `JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class`

### Possible Solutions

Maybe it's related to submenu filtering.

**Comment by Shidersz** [comment]
Have you published the main views previously? If yes, please follow the [Update Procedure - Step 3](https://github.com/jeroennoten/Laravel-AdminLTE#3-updating), because the new release also includes changes to the views that affects the submenu items. Remember to backup your views before publishing the new ones if you have changed they.
