### ISSUE TITLE
Admin LTE Laravel config:clear not working

### ISSUE THREAD

**Issue by konoha-lab** [jeroennoten/Laravel-AdminLTE#663]
hi. me to have the problem with new adminLTE v3. config:clear don't work . i should run php artisan adminlte:install --only=config in order to take effect. what did i miss.?

**Comment by Shidersz** [comment]
Hi @konoha-lab 

> have the problem with new adminLTE v3

Could you provide more details of your problem? Actually `config:clear` is used to remove the Laravel cache file generated by [config:cache](https://laravel.com/docs/7.x/configuration#configuration-caching), if you don't have a cached file, then **Laravel** framework will search into the `config/` folder in order to get configuration values.

On the other hand the `adminlte:install --only=config` command, will install/update with the latest configuration file provided with this package, this means that if you have changed some values, after executing this command and confirm the overwrite warning, you will get the default package config installed on `config/adminlte.php` file.

Now, having this clear, what is the problem you are facing?

**Comment by konoha-lab** [comment]
hi @Shidersz ,
Thank for your response, actually i have change adminlte config to change menu on admin LTE. i always using _Config:Clear, Cache:Clear_ when the menu hasn't been changed, to apply with my change. and it works fine when i use the previous version.

but after i using latest AdminLTE V3. i dont know using Config:Clear, Cache:Clear did not take effect. i still face cache menu. not my latest change. 

i should type _adminlte:install --only=config_ to make it work.

**Comment by Shidersz** [comment]
There was a similar issue some time ago, take a look to ISSUE #601. The issue was related to some conflicting packages, but the user did not explain what packages, maybe you can ask there what packages was generating the conflict. If that do not help, I will give a better review to the problem.

**Comment by konoha-lab** [comment]
ok thanks, i will take a look to isse #601 .
