### ISSUE TITLE
problem with using datatables

### ISSUE THREAD

**Issue by ageurtse** [jeroennoten/Laravel-AdminLTE#683]
i have written a piece of test code, but can't get it to run. 

this is what i have so far
**blade.php file**
```@extends('adminlte::page')

@section('title', 'Home')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <h1>Test run</h1>
    <table class="table table-bordered data-table">
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Email</th>
                <th width="100px">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Test'); </script>

    <script type="text/javascript">
        $(function () {

          var table = $('.data-table').DataTable({
              processing: true,
              serverSide: true,
              ajax: "{{ route('users.index') }}",
              columns: [
                  {data: 'id', name: 'id'},
                  {data: 'name', name: 'name'},
                  {data: 'email', name: 'email'},
                  {data: 'action', name: 'action', orderable: false, searchable: false},
              ]
          });
        });
      </script>
@stop
```

**Controler file**
```<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use DataTables;

class UserController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = User::latest()->get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){

                           $btn = '<a href="javascript:void(0)" class="edit btn btn-primary btn-sm">View</a>';
                           return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }   return view('users');
    }
}
```

**and my adminlte.php config file** 

```   'plugins' => [
        'Datatables' => [
            'active' => true,
            'files' => [
                [
                    'type' => 'js',
                    'asset' => true,
                    'location' => '//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js',
                ],
                [
                    'type' => 'js',
                    'asset' => true,
                    'location' => '//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js',
                ],
                [
                    'type' => 'css',
                    'asset' => true,
                    'location' => '//cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css',
                ],
            ],
        ],
```

and this is a part of the error i get.

>     "message": "Class 'DataTables' not found",
>     "exception": "Error",
>     "file": "C:\\xampp\\htdocs\\test\\app\\Http\\Controllers\\UserController.php",
>     "line": 20,

I can't figure out what is wrong, i'm usig Laravel 7.

**Comment by Shidersz** [comment]
> "message": "Class 'DataTables' not found",
> "exception": "Error",
> "file": "C:\\xampp\\htdocs\\test\\app\\Http\\Controllers\\UserController.php",
> "line": 20,

The previous message means that the `DataTables` class can't be found when you reference it inside the  `UserController.php` file. Using `google` I suspect you are trying to use the next package: [yajra/laravel-datatables](https://github.com/yajra/laravel-datatables). If so, please refers to the [Quick Installation Section](https://github.com/yajra/laravel-datatables#quick-installation). Maybe you have forgotten to include the alias on the config file:

```php
'aliases' => [
    ...,
    'DataTables' => Yajra\DataTables\Facades\DataTables::class,
]
```

Or you can try replacing `use DataTables;` by `use Yajra\DataTables\Facades\DataTables;` on the controller file. There is also an example you can follow:

https://www.positronx.io/laravel-datatables-example/

However, I can't be really sure since I have never used this package before.

**Comment by ageurtse** [comment]
no i don't knwo which one is used within this package, isn't it pre installed when use this template ?

**Comment by ageurtse** [comment]
Installed through Yajra and now it's working. 
In my opnion it should be written out that is makes use of the Yarja package. 
Or how to use de datatables with this package.

**Comment by Shidersz** [comment]
Hi @ageurtse , for what I know **Yajra** is not part (or required) by this package. Maybe, in your local project someone has executed `composer require yajra/laravel-datatables...`. This packages includes, but only **optionally** the `Datatables` plugin for the client-side (to use with `javascript/jquery`). For what I have read, the `Yajra` package is an extension for use `Datatables` on the server-side (with `php`).

**Comment by ageurtse** [comment]
No it was not installed, i just did it manualy. 
As a beginner i could not find it on this github that i have to manual install the datatables from yajra. 
I found that package already, but didn't think that i had to install it. 

so for now it is solved, thanks a lot.

**Comment by Shidersz** [comment]
@ageurtse Please, give a read to [Plugins Section](https://github.com/jeroennoten/Laravel-AdminLTE#613-plugins) to understand how to configure the package config file in order to enable additional **client-side** plugins (like `Datatables`). Also, in case you won't use the `CDN` for plugins, you can use the `php artisan adminlte:plugins` command to see a list of what **client-side** plugins are available to install locally, and refer to [Plugin Command Section](https://github.com/jeroennoten/Laravel-AdminLTE#52-the-adminlteplugins-command) to check how to install these plugins. Anyway, after installing a plugin locally you will still need to configure it on the `adminlte.php` config file.

And again, the `yajra/laravel-datatables` package is external and independent of this package, it provides a way to manage `Datatables` on the server side. The usage of that package will depend if you need that feature or not.
