### ISSUE TITLE
Sidebar does not open on mobile

### ISSUE THREAD

**Issue by jonasmarco** [jeroennoten/Laravel-AdminLTE#707]
| Question                    | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version                | 8.x
| Project Version                | Last

Guys, someone can help me? The sidebar isn't opening on mobile.

![](https://i.imgur.com/14CIuFE.jpg)
![](https://i.imgur.com/lCWUuNt.jpg)

**Comment by Shidersz** [comment]
Hi @jonasmarco , I believe the problem is related to the `sidebar_collapse_auto_size` configuration option, if you set it to `false` it will work fine. For what I can read on [Documentation](https://github.com/jeroennoten/Laravel-AdminLTE#73-sidebar) that option appears to accept a number or `false` to disable it.

- __sidebar_collapse_auto_size__: Enables/Disables auto collapse by setting a minimum width to auto collapse.

Maybe @REJack can clarify how to use that option and what it is supposed to do, so we can update the documentation later.

**Comment by jonasmarco** [comment]
@Shidersz That's right, it helped me, thanks
