### ISSUE TITLE
Search is not responsive and too big

### ISSUE THREAD

**Issue by MTEXX** [jeroennoten/Laravel-AdminLTE#727]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | 7
| Project Version         | v3.5.0

### Current Behavior

![image](https://user-images.githubusercontent.com/3194660/94737938-f3699180-036e-11eb-8363-2589f3d77d06.png)

Search is not responsive and too big compared to the AdminLTE 3 Demo (see https://adminlte.io/themes/v3/).

### Expected Behavior

![image](https://user-images.githubusercontent.com/3194660/94737960-fd8b9000-036e-11eb-85e9-fca4058daffc.png)

Search is responsive and smaller.

### Possible Solutions

PR will be available shortly.

**Comment by lacodimizer** [comment]
@REJack @Shidersz any idea to solve it without breaking changes.

**Comment by Shidersz** [comment]
@lacodimizer I have mentioned an alternative solution on #728 , using `imput-group-sm` to minimize the size and improve it to read `classes` attributes so the user can hide when the screen width is not enough. I will check if there is a better solution when get some time...

**Comment by MTEXX** [comment]
Why hide the input field instead of formatting it the right way? In the AdminLTE template it shows right even on small displays without hiding the field.

**Comment by Shidersz** [comment]
Hi @MTEXX, on the [AdminLTE site](https://adminlte.io/themes/v3/) the `Home` and `Contact` links follows that logic, they are hidden to liberate space for the search bar when the screen width is low. There is no easy way to get multiple elements in the top navbar when the screen width is too low. Ideally, a collapsible search bar that overlays over the entire navbar will be better, but that is no easy to implement. Also, we have to take into consideration that position is not fixed, it can be placed anywhere, since is configured from a menu item. I was not thinking on hide it as a default behavior, but if we let it read classes from the menu configuration, then the user has the possibility to define own classes and give it some extra customization.

**Comment by Shidersz** [comment]
To help understand what is happening, here you have an screenshot of the demo site without `Home` and `Contact` links hidden:

![Screenshot_2020-10-04 AdminLTE 3 Dashboard](https://user-images.githubusercontent.com/63609705/95017907-55a5e900-0632-11eb-84b1-2043b3c3578a.png)

As you see, there is an overflow of the right sidebar toggle icon. So, using the same html format provided there won't give a general solution to the problem. To prevent that overflow, we can use `flex-wrap` class on the left and right navbar sections, but in that case, menu items will spawn over multiple rows:

![with_flex_wrap](https://user-images.githubusercontent.com/63609705/95018009-22b02500-0633-11eb-9fc0-f5e355eb6578.png)

IMO I believe `flex-wrap` should be used. I prefer to avoid that overflow and see all the available menu items on the `navbar`. On the other hand, we should find a solution to auto collapse that search bar into an icon or something that takes less space on `sm` and `xs` screens. Maybe the incoming new AdminLTE version mentioned here #674 will give us some help on that.

@REJack , @lacodimizer , @MTEXX what do you think ?

**Comment by resslinger** [comment]
@REJack

**Comment by REJack** [comment]
With AdminLTE v3.1.0 comes a new navbar search this would eliminate this bug.
