### ISSUE TITLE
QUESTION: Top Nav Menu

### ISSUE THREAD

**Issue by samuel-lujan** [jeroennoten/Laravel-AdminLTE#730]
Can I change the layout options, to only one page of my website?

**Comment by Shidersz** [comment]
Probably yes, since you can change [configuration at runtime](https://laravel.com/docs/8.x/configuration#accessing-configuration-values) on Laravel. You can change the configuration on the controller, before loading (rendering) your view, for example:

```php
config([
    'adminlte.layout_topnav' => true,
    'adminlte.layout_fixed_navbar' => true,
]);
```

I'm not sure if the changes will persists for every request, in that case you will need to restore the configuration value for all the other views.

**Comment by samuel-lujan** [comment]
Oh that's pretty cool, but how can I change this at my controller? only add this code? or I'll need change more things?

**Comment by samuel-lujan** [comment]
Oh! that's look good! Thanks! :)
