### ISSUE TITLE
Recaptcha Plugin or guide recommended?

### ISSUE THREAD

**Issue by fbc** [jeroennoten/Laravel-AdminLTE#758]
I tried to follow a few guides to integrate recaptcha with the AUTH views for ADMIN LTE but failed.

Is there a plugin for ADMINLTE available or a preferred guide?

**Comment by Shidersz** [comment]
Hi @fbc, I'm not really sure is there is a plugin available, you can try opening a question/issue on [AdminLTE package](https://github.com/ColorlibHQ/AdminLTE). Also, next guide may help you:

https://bootstrapious.com/p/bootstrap-recaptcha

What you need to know, is that when you submit one of the authentication forms, a `POST` is made to the Laravel route registered with it. On the login form, for example, you can see:

```blade
<form action="{{ $login_url }}" method="post">
```
By default, `$login_url = 'login'` on the configuration file, and you will have to figure out how Laravel catches that route internally and what controller is assigned to it in order to make modifications. The other possibility may be to try solve all from **client-side** (`Javascript`) and disable the submit of the form until the captcha verification is done.
