### ISSUE TITLE
Datatables not connecting through adminlte.php

### ISSUE THREAD

**Issue by raysultan** [jeroennoten/Laravel-AdminLTE#773]
Hey Mates, I am not able to connect Datatables through adminlte.php I've updated cdn links and also tried to connect it to adminlte plugins not it didn't work finally I went for the @section('js') and pasted the cdn link there it Worked but I wonder why isn't it working through adminlte?

**Comment by Shidersz** [comment]
Please, share the configuration you have for the `Datatables` plugins on the confguration file (`adminlte.php`). Or all the configuration for the `plugins` array.

**Comment by raysultan** [comment]
![Datatables Pic](https://user-images.githubusercontent.com/74557763/100513753-31c3d700-318d-11eb-94a1-8b26fd90fdbe.PNG)


Here's the code

**Comment by Shidersz** [comment]
Note the `active` property for **Datatables** plugin is `false`. When `true` the files will be included on all the views extending the layout with the sentence `@extends('adminlte::page')`. Otherwise, you need to manually include the plugin files on the view you going to use it with the sentence `@section('plugins.Datatables', true)`. Take a look to [Plugins Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/9.-Other-Configuration#91-plugins).

**Comment by raysultan** [comment]
Hey buddy it Worked, Thank you for your kind information :)
