### ISSUE TITLE
Cant figure out the blade file for adminlte::page

### ISSUE THREAD

**Issue by 1sps** [jeroennoten/Laravel-AdminLTE#775]
Which file is called when I use @exteds('adminlte::page') ? I want to go to head section and add my custom javascript but i cant figure out where the bladed file for that page is.

Please help. Thanks.

**Comment by Shidersz** [comment]
Hi @1sps , to edit the package blade files you first need to [publish the views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/11.-Customize-Views). Then, in your case, you will want to edit the `resources/views/vendor/adminlte/master.blade.php` to change the **head** section.

However, the recommendation to include custom `javascript` is to use the [Plugins Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/9.-Other-Configuration#91-plugins) on the `config/adminlte.php` file, example:

```php
'plugins' => [
    ...
    'MyCustomFiles' => [
        'active' => true,
        'files' => [
            [
                'type' => 'js',
                'asset' => true,
                'location' => 'vendor/custom-files/js/file1.js',
            ],
            [
                'type' => 'css',
                'asset' => true,
                'location' => 'vendor/custom-files/css/file2.css',
            ],
            ...
        ],
    ],
]
```

Since all the extra plugins files are on the `vendor` folder, it is a good practice to put the custom files there too. Read the documentation to see what `active => true` means, and how you can include the files only on particular blade files using the `@section('plugins.MyCustomFiles', true)` directive. Another alternative, is to use the exported `js` package section to include extra `javascript` on any particular blade file:

```blade
@push('js')
    <script src="{{ asset('vendor/custom-files/js/file1.js') }}"></script>
@endpush
```

**Comment by 1sps** [comment]
Thanks for replying ans showing different ways to do what I want. Solved my problem.
