### ISSUE TITLE
[Question] Is there any configuration to show the logo only on the login page?

### ISSUE THREAD

**Issue by jonasmarco** [jeroennoten/Laravel-AdminLTE#787]
Hi guys,

There is some configuration that allows you to display the logo only on the login page. Or would you have to add a css for that?

**Comment by Shidersz** [comment]
Hi @jonasmarco , you can setup the configuration `'logo_img_class' => 'd-none'` to hide the logo image after login. In you want to also hide the brand text, you can use `'classes_brand' => 'd-none'`.

**Comment by jonasmarco** [comment]
Thank u guy.

**Comment by royallife88** [comment]
Hi @Shidersz , I want dynamically change the logo of the login page. I tried the event service provider method for the logo, it is working fine in the dashboard logo but not for the login page logo. How I can change the login page logo also the same as the dashboard logo.

**Comment by Shidersz** [comment]
Have you tried to set the [configuration dynamically](https://laravel.com/docs/9.x/configuration#accessing-configuration-values) on the `boot()` method of the `app/Providers/AppServiceProvider.php`? I don't know what you mean with dynamically, in the case the logo is stored on the database, you may also try to publish the package view, and edit the login view to get the path from the database instead of the getting from configuration, or use `php` to setup the config in the first lines of the blade view...
