### ISSUE TITLE
icons and table box style is not appearing

### ISSUE THREAD

**Issue by alwaysinfotech** [jeroennoten/Laravel-AdminLTE#794]
I am using Laravel version 7 and installed "jeroennoten/Laravel-AdminLTE"

I am trying to use simple adminlte table but white box styling is not appearing and icons are also not appearing. Please see following screenshots.

![2](https://user-images.githubusercontent.com/36074941/103736539-78bbac80-5016-11eb-8414-e1de9d24acf7.png)
![1](https://user-images.githubusercontent.com/36074941/103736554-82451480-5016-11eb-828c-c30bee6238ed.png)

I checked [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/1.-Requirements) complete documentation as well but did not get any clue.

**Comment by Shidersz** [comment]
Hi @alwaysinfotech , I don't understand, are you using this package or a custom integration of [ColorlibHQ/AdminLTE](https://github.com/ColorlibHQ/AdminLTE). If you are using this package, the [Font Awesome v5](https://fontawesome.com/) are included within the package. But you should use `<i class="fab fa-google-plus"></i>` instead of `<i class="fa fa-google-plus"></i>`. On the other hand, to use ion icons you may need to manually include the files for that plugin, one options is to use `CDN` files and the other to donwload files locally inside `public/vendor/<plugin-name>` folder. In both cases check section [Plugins Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/9.-Other-Configuration#91-plugins) to see how to include plugins using the package configuration file.

**Comment by alwaysinfotech** [comment]
Sorry I mentioned wrong package, I updated my question, Actually I used "jeroennoten/Laravel-AdminLTE" for using adminlte in Laravel. 2 problems, I am facing

- First icons were not appearing
- Second, I am using adminlte simple table, as you can see its CSS not loading, when you use, <div class="box"> then white background should box in table but it is not appearing .

**Comment by Shidersz** [comment]
Hi @alwaysinfotech , for the icons, check my previous comment. For these [Simple Tables](https://adminlte.io/themes/dev/AdminLTE/pages/tables/simple.html), they inherit the background color for what I have tested. In the examples they show, the tables are wrapped by `.card` elements, and the white background comes from these cards. You can use the browser's inspector tool to see how markup is structured on the examples.

**Comment by resslinger** [comment]
@alwaysinfotech the tables has the background style of the boxes around the table by default. You can test it, if you open https://getbootstrap.com/docs/4.0/content/tables/ and change the background color of the page. The tables has the same background color too.
