### ISSUE TITLE
JS not working properly in Laravel 8

### ISSUE THREAD

**Issue by DesarrolloProm** [jeroennoten/Laravel-AdminLTE#797]
I'm working in a new project everything was working fine and after I installed "jquery-ujs" to use modals, I found out that the usermenu doesn't show, I have all the options on 'true'.

 This happens when I put :

partials/adminlte:

` @section('js')
   <script src="{{asset('js/app.js')}}"></script>
@stop`

In my partial file (I'm using the basic layout as a partial so I can use it where it want), if I delete that the usermenu works fine but then I can't use modals.

this is what I have in my resources js file:

resources/js/app.js:
`require('./bootstrap');
require('jquery-ujs');
require('./remote');`

and this is what I have in my remote,js: 

resources/js/remote.js:
`$(document).on('ajax:success', function(e, xhr){
    if(!$('#myModal').length){
        $('body').append($('<div class="modal" id="myModal"></div>'))
    }
   $('#myModal').html(xhr).modal('show');
});`

idk if it's a bug or else

**Comment by Shidersz** [comment]
@DesarrolloProm Let me understand, the problem appears after you add the next code into a custom view that `@extends('adminlte::page')` ?

```blade
@section('js')
    <script src="{{asset('js/app.js')}}"></script>
@stop
```

On the other hand, if you expects to use **Laravel Mix** to include new plugins and or custom scripts, then you will have to enable the configuration [enable_laravel_mix](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/9.-Other-Configuration#92-laravel-mix). I recommend you to review file [master.blade.php](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/master.blade.php) to see how logic works when `enable_laravel_mix` is enabled.

The usage of this file: `resources/js/app.js` gives me suspect that you wants to use **Laravel Mix**, and in that case, you will need to enable it on the package and see how it works, otherwise conflicts between the base plugins files and the ones you include with mix will be generated.

**Comment by DesarrolloProm** [comment]
Mm yes, well I created a file that look like this:

partials/adminlte:
`@extends('adminlte::page')

@section('content_header')
@yield('header')
@stop

@section('content')
@yield('content')
@stop

@section('css')

@stop

@section('js')
<script src="{{asset('js/app.js')}}"></script>
@stop`

So I can use adminLTE in all my project, idk if that's the way to do it but it worked for me, and if I erase the: `<script src="{{asset('js/app.js')}}"></script>` usermenu works.

**Comment by DesarrolloProm** [comment]
I enabled Laravel Mix and I worked, thanks
