### ISSUE TITLE
Change logo on sidemenu if sidemenu is collapsed

### ISSUE THREAD

**Issue by MathiasOliveira** [jeroennoten/Laravel-AdminLTE#820]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Question
| Laravel Version         | v8.28.1
| Project Version         | v3.5.2

### Current Behavior

Currently the logo and text stays on while the menu is extended and when the menu is collapsed it shows only the logo

### Desired Behavior

I have changed the `brand-logo-xs.blade.php` file to this:

```html
<a href="{{ $dashboard_url }}"
    @if($layoutHelper->isLayoutTopnavEnabled())
        class="navbar-brand {{ config('adminlte.classes_brand') }}"
    @else
        class="brand-link {{ config('adminlte.classes_brand') }}"
    @endif>

    {{-- Small brand logo --}}
    <img src="{{ asset('vendor/adminlte/dist/img/logo.svg') }}"
         alt="Nexello SGN"
         class="brand-image img-circle elevation-3"
         style="opacity:.8">

    {{-- Brand text --}}
    <img class="img-responsive ml-4" src="{{ asset('vendor/adminlte/dist/img/brand.svg') }}" height="33"/>

</a>
```
And I would like to show the "Small Brand Logo" if the menu is collapsed/close and when the menu is open only show the Brand text.
Example (made with inspect element):

Extended menu:
![image](https://user-images.githubusercontent.com/67007152/109707809-5eff9700-7b79-11eb-9a9c-e4eceaa5cad8.png)

Collapsed menu:
![image](https://user-images.githubusercontent.com/67007152/109707841-6a52c280-7b79-11eb-9f1f-0d36002aeac0.png)

How it looks at the moment:
![image](https://user-images.githubusercontent.com/67007152/109707945-89515480-7b79-11eb-86e4-54c263ad57e3.png)

**Comment by Shidersz** [comment]
Hi @MathiasOliveira , on the configuration file you have the option to configure two logos (See [Logo Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration#logo)):

- **logo_img:** The path to the small logo image. The recommend size is: `50x50px`.
- **logo_img_xl:** The path to the large logo image, if you set a img url here, then it will replace the text & small logo with one big logo. When the sidebar is collapsed it will displays only the small logo. The recommend size is: `210x33px.`

So, instead of a **logo image** and a **text**, you can use two **logo images**, one (small) for the collapsed mode and another (large) for standard mode. Maybe, that fits your needs...

**Comment by MathiasOliveira** [comment]
That is exactly what I wanted, who would've guessed, following documentation was the better way than doing things my way 😂 

Thank you for your help.
