### ISSUE TITLE
Navbar user info bug when using tailwind

### ISSUE THREAD

**Issue by DesarrolloProm** [jeroennoten/Laravel-AdminLTE#823]
| Question                | Answer
| Laravel Version         | 8.*

### Current Behavior

Hi, I have a bug in my navbar when I'm importing tailwind, and idk why is this happening.

I know that bootstrap and tailwind doesn't work well together, so I'm using a prefix in all my tailwind classes "tw-", anyone have any idea of how to "fix" it

_**tailwind.config.js**_

![image](https://user-images.githubusercontent.com/75850851/110719528-a1a51d00-81d2-11eb-9fe7-88c0f8b9e5fa.png)

**Error/bug**

![image](https://user-images.githubusercontent.com/75850851/110719609-c00b1880-81d2-11eb-8747-1a92f46db7db.png)

 **Expected**

![image](https://user-images.githubusercontent.com/75850851/110719655-d4e7ac00-81d2-11eb-905d-f05836d98c8c.png)

**Comment by Shidersz** [comment]
@DesarrolloProm I'm not sure if it is a good idea to use both libraries. This package comes with **Bootstrap**, and we can't ensure/support it to work with **Tailwind**. However, have you read [Adding Tailwind Classes To Boostrap](https://www.scottbrady91.com/General/Adding-Tailwind-Utility-Classes-to-your-Bootstrap-Website)?

Good luck with your integration! Take into consideration to share the steps if you get it work, thanks!

**Comment by jsalmoralp** [comment]
Hello @DesarrolloProm 

I have had the same problem when adding the two libraries (the BOOTSTRAP integrated with this package, and the TAILWIND that comes with Laravel 8), my solution is the one you see in my Fork, although it can be improved.

Since when we open the user menu, if it has a very short name, it could make the user image appear next to it and not on top as it should be. but this is easy by adding an extra pair of "div".

PS: Surely when you read this, the improvement I was talking about is already applied to my Fork.

And now thinking ... I will also add the code of my "mix", as well as the files it is calling to generate my "css" and "js", in addition to the main template file of my current project; So that there is no doubt that it has to be imported, and when / where / and the correct positioning of the import.
