### ISSUE TITLE
User menu is enabled but not being displayed on navbar

### ISSUE THREAD

**Issue by arthurmgb** [jeroennoten/Laravel-AdminLTE#839]
Laravel version: 8.*

### Current Behavior

User menu is enabled but it's not being displayed

![issue](https://user-images.githubusercontent.com/62814691/112561668-6c90f100-8db4-11eb-9609-d9e1f59f7b22.png)

### Expected Behavior

![issue2](https://user-images.githubusercontent.com/62814691/112562182-81ba4f80-8db5-11eb-98d1-9ff02f8e3da8.png)

**Comment by Shidersz** [comment]
Hi @arthurmgb , the usermenu will not be displayed if you do not have an authentication scaffolding installed, since It check if any user is authenticated before displaying anything. Have you installed some authentication scaffolding and running the database migrations for Laravel? If not, please take a read to **step 3** of [Installation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation) and the suggested links...

**Comment by arthurmgb** [comment]
Thank you, it worked after jetstream installation.
