### ISSUE TITLE
Question : Add variable to dynamic menu

### ISSUE THREAD

**Issue by castorius31** [jeroennoten/Laravel-AdminLTE#844]
Hi, I would like to create a dynamic menu with the id of the current record to create a contextual menu. 
I try `$this->events->listen(BuildingMenu::class, function (BuildingMenu $event)` with something like
`$event->menu->add('text'=>'function',    'url' => URL::to('records/' . $record->id . '/add'));`
but i don't know how i can pass the current id.
Is it possible or not ?

Regards

Christophe P.

**Comment by Shidersz** [comment]
I believe you need to use the `use` sentence on the closure in order to access an external variable. For example:

```php
$events->listen(BuildingMenu::class, function (BuildingMenu $event) use ($record) {
    /* ... */
    $event->menu->add([
        'text'=>'function',
        'url' => URL::to('records/' . $record->id . '/add')
    ]);
});
```

Note that new menu items are expressed as an array with properties.
More info: https://stackoverflow.com/questions/1065188/in-php-what-is-a-closure-and-why-does-it-use-the-use-identifier

**Comment by castorius31** [comment]
Hi Diego, Thanks a lot. I'm not used to using closure function.
Regards
Christophe P
