### ISSUE TITLE
[QUESTION] how can i change the font?

### ISSUE THREAD

**Issue by allanpedroso** [jeroennoten/Laravel-AdminLTE#864]
where do I change the font?

**Comment by Shidersz** [comment]
@allanpedroso I believe there is no configuration option for that. I think (but not really sure) that the used font is related to **Bootstrap** or the underlying **AdminLTE** package. However, I have experimented and you can change the font on your pages that `@extends()` the layout provided by this package with something like next (for example):

```blade
@extends('adminlte::page')

@push('css')
<style type="text/css">
    body {
        font-family: cursive !important;
    }
</style>
@endpush

{{-- Other code related to your page --}}
```

In this case, it will be better that you create a new base layout with the previous code, and make your pages extends this new layout instead of the `page` layout provided by the package. This way, you can keep all customization in one place.

@REJack Do you have any other clue about this?

**Comment by dfsmania** [comment]
A solution was provided...
