### ISSUE TITLE
[BUG] Sidebar doesn't load options

### ISSUE THREAD

**Issue by DesarrolloProm** [jeroennoten/Laravel-AdminLTE#886]
### Describe the bug
I was adding breadcrumbs to my project, and after updating composer, installing _diglactic/laravel-breadcrumbs_ and publish the configuration file my sidebar stopped loading my options.

expected
![image](https://user-images.githubusercontent.com/75850851/117176899-04133780-ad96-11eb-99bc-d59f1bff5e85.png)

now
![image](https://user-images.githubusercontent.com/75850851/117176937-0f666300-ad96-11eb-86fc-3fb8963b5ebf.png)

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | 
| OS      |

**Comment by Shidersz** [comment]
@DesarrolloProm May be a deployment issue, or some error in your files after the installation / updating procedure. Try next options:

1. Check the Laravel log file for errors (`storage/logs/laravel.log`).
2. Check that the `config/adminlte.php` file wasn't overwritten.

**Comment by DesarrolloProm** [comment]
It´s clearly a deployment issue or something when I run `composer update`, so I don't think it's a bug.

**Comment by DesarrolloProm** [comment]
Quick update: I figured up why is this happening, It turns out that because I'm using Laratrust to define roles and permissions, the 'can' part in menu wasn't taking into account that my user had the permissions to see those options. 

![image](https://user-images.githubusercontent.com/75850851/117214974-2d968800-adc3-11eb-870b-817e12f376a2.png)

if I use that I can see the option without the "can", but the other doesn't work.

Does that make any sense ?

**Comment by Shidersz** [comment]
Take a read to [Custom Menu Filters](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#custom-menu-filters), there is an example of how to implement a custom filter with Laratrust and remove the built-in one that uses [Laravel Gate](https://laravel.com/docs/8.x/authorization#gates). On the example, it is assumed that you will use the `permission` attribute on the menu items instead of the `can` attribute. If your project already has the custom filter created, review the logic. Note you can't use the built-in filter with Laratrust, you need to make your own filter.

**Comment by DesarrolloProm** [comment]
That worked, thanks!
