### ISSUE TITLE
Call to undefined method JeroenNoten\LaravelAdminLte\Helpers\MenuItemHelper::transform() 

### ISSUE THREAD

**Issue by teTorrian** [jeroennoten/Laravel-AdminLTE#913]
I did a composer update to upgrade to 3.6.0 cause I wanted to use the new x-blade components and the first error I got was:

Call to undefined method JeroenNoten\LaravelAdminLte\Helpers\MenuItemHelper::isSearchBar()

After that I included MenuItemHelper::class into the filters array in adminlte.php. Now I'm stuck on following error:

Call to undefined method JeroenNoten\LaravelAdminLte\Helpers\MenuItemHelper::transform()

Did I miss something during the update procedure? Any advice? Thanks in advance!

**Comment by Shidersz** [comment]
@teTorrian 

> After that I included MenuItemHelper::class into the filters array in adminlte.php

Why you have done that? Thar is really wrong! Please remove that class from the filters array.

The first error you see may be because you have published the package views. In that case, you need to update those published views manually. Check issue #905 , there is a discussion on how to solve this.
