### ISSUE TITLE
[QUESTION] Prefix in menu url

### ISSUE THREAD

**Issue by warquia** [jeroennoten/Laravel-AdminLTE#923]
Good night friends. is there any way to put a prefix in the menu url?

My users will have different urls for each 
Ex; mysite.com/jonh/posts
mysite.com/maria/post 
etc...
but inside "config/adminlte" the links are static. Is there an option to prefix a urls?

**Comment by Shidersz** [comment]
@warquia You can't access the current user or any other property related to a request/response cycle from the configuration file. When the menu depends on the current authenticated user you can try to [build the menu at runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime), or at least those menu items that needs to be dynamically generated. Another possibility can be to define a static url like `mysite.com/posts` and get the authenticated user using the [Auth Facade](https://laravel.com/docs/8.x/authentication#retrieving-the-authenticated-user) on the controller, in order to return the related post.

**Comment by warquia** [comment]
Thanks a lot for the help !!. I didn't know there's a way to build the menu at runtime, tomorrow I'll test it and return with the results!

**Comment by warquia** [comment]
Thanks @Shidersz the runtime menu worked for me.
