### ISSUE TITLE
User menu only works on home

### ISSUE THREAD

**Issue by dfe-dev** [jeroennoten/Laravel-AdminLTE#928]
### Describe the bug
User menu (right side) is working fine, but just in the home page. After extending other existing views (using official instructions), AdminLTE is displayed with the view content, but user menu is not popping up after clicking on username or photo.

### Steps To Reproduce
1.  Extend the layout of existing view with @extends('adminlte::page')
2. Click on username or user photo
3. User menu doesn't pop up

### Expected behavior
User menu should appear with profile and logout buttons.

### Environment

| Item    | Version
| ------- | -------
| Laravel |  v8.28.1
| Project | AdminLTE v3
| OS      | Ubuntu 20.04.2.0 LTS

**Comment by Shidersz** [comment]
@dfe-dev Please check for error on the browser's console, maybe there is something that can help to track the problem. If you do not found a solution, create a minimal example and share the view, controller, routes and other things you may consider important. I have it working on my local environment, so probably the problem is related to your integration with the laravel framework.

**Comment by Shidersz** [comment]
Closed, no feedback!
