### ISSUE TITLE
[FEATURE] Datatables server side

### ISSUE THREAD

**Issue by hanafiazra99** [jeroennoten/Laravel-AdminLTE#931]
How can i use datatable server side using template x admin lte?

**Comment by Shidersz** [comment]
Read the [Datatables Server Side Documentation](https://datatables.net/examples/data_sources/server_side). To setup the plugin initial configuration, you may use the `config` property of the component. Read details of the component [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Tool-Components#datatables). On the example, they initialize the table like this:

```javascript
$(document).ready(function() {
    $('#example').DataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "../server_side/scripts/server_processing.php"
    } );
} );
```

You can do similar initialization with...

```blade
{{-- Setup datatables config --}}
@php

$config = [
    'processing' => true,
    'serverSide' => true,
    'ajax' => "{{ url('<ajax_url>') }}",
];
@endphp

<x-adminlte-datatable id="myTable" :config="$config" ... />
```

I can't help you anymore because never tried this feature, but you may follow guides from the internet to check how to implement the server-side code.

**Comment by hanafiazra99** [comment]
thank you for your help, it works

**Comment by Shidersz** [comment]
Glad to know you get it to work!
