### ISSUE TITLE
[FEATURE]Ability to show flash messages as part of the template

### ISSUE THREAD

**Issue by joelconty** [jeroennoten/Laravel-AdminLTE#954]
### Is your request related to a problem? Please describe.
My admin page is supposed to display success|error messages when an action is taken.
Right now I don't see the way to do that, other than adding a section in each of the page contents, of all my admin pages, creating repetitive code.  

### Describe the solution you'd like
The ideal solution would be that the AdminLte template had a "flash messages" section that would appear if there are any error|success messages to show.

### Describe alternatives you've considered
none

**Comment by Shidersz** [comment]
@joelconty Maybe you can try the next package:

https://github.com/WadeShuler/laravel-flashmessages

On the other hand, there is no need to repeat the code on all your pages, since you can create your own base page with your own extensions and/or customizations, and make all the other views extends from it. The idea is somehow explained on the next closed issue:

https://github.com/jeroennoten/Laravel-AdminLTE/issues/925
