### ISSUE TITLE
[QUESTION] How to use required assets from CDN ?

### ISSUE THREAD

**Issue by phuhung273** [jeroennoten/Laravel-AdminLTE#969]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    |Enhancement
| Laravel Version         | 8.40
| Project Version         | 3.6.1

### Current Behavior

Load basic assets(bootstrap, jquery, adminlte, popper,..) from server

### Expected Behavior

How to load all basic assets from CDN ?

**Comment by Shidersz** [comment]
Hi @phuhung273 , they are load from server because these are the know versions that works with AdminLTE underlying package. Actually, most of the plugins (jquery, popper, etc...) comes from the AdminLTE package (they are copied to the laravel `vendor` folder on the installation procedure). For example, **AdminLTE** still do no work with `Bootstrap 5`.

However, if you are sure what you will do, you can [publish](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) the main views, and then change `resources/views/vendor/adminlte/master.blade.php` file to include files from `CDN` instead of including they from vendor folder. At next you can see the section of the mentioned file that defines the `<body>` tag and what changes you will need to do (note you will need to do similar changes on the `<head>`).

```blade
<body class="@yield('classes_body')" @yield('body_data')>

    {{-- Body Content --}}
    @yield('body')

    {{-- Base Scripts --}}
    @if(!config('adminlte.enabled_laravel_mix'))
        {{-- ************************************************ --}}
        {{-- Change next definitions to include they from CDN --}}
        {{-- ************************************************ --}}
        <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
        <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ asset('vendor/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>CDN --}}

        {{-- Configured Scripts --}}
        @include('adminlte::plugins', ['type' => 'js'])

        <script src="{{ asset('vendor/adminlte/dist/js/adminlte.min.js') }}"></script>
    @else
        <script src="{{ mix(config('adminlte.laravel_mix_js_path', 'js/app.js')) }}"></script>
    @endif

    ...
    ...
    ...

</body>
```

**Comment by phuhung273** [comment]
@Shidersz I didn't pay attention to the Wiki sidebar to see the View Customization section.
This can question can be closed now.
Thank you so much for supporting.
