### ISSUE TITLE
[BUG] Navbar in Darkmode stays white and light

### ISSUE THREAD

**Issue by invaders-xx** [jeroennoten/Laravel-AdminLTE#970]
### Describe the bug
Clicking the dark mode toggle switch every content to dark, except the navbar. Did I miss something ?

### Screenshots
<img width="798" alt="image" src="https://user-images.githubusercontent.com/604907/130414773-8b66409d-306f-4e32-93af-2b47d97cf5fe.png">

### Environment

| Item    | Version
| ------- | -------
| Laravel | 8
| Project | v3.7.0
| OS      |  OSX

**Comment by Shidersz** [comment]
Hi @invaders-xx , It works like on the underlying **AdminLTE package**, you can test it [here](https://adminlte.io/themes/v3/), open the right control sidebar and check the dark mode option.

Feel free to open an issue on the [AdminLTE package](https://github.com/ColorlibHQ/AdminLTE), since this style concept is related to that package.

**Comment by invaders-xx** [comment]
My apologies! You're right and I'am wrong. I thought that the navbar should also change. Many thanks for your quick feedback.
