### ISSUE TITLE
[Question] How to apply input mask to x-adminlte-input component?

### ISSUE THREAD

**Issue by cezarsanti** [jeroennoten/Laravel-AdminLTE#975]
### Is your request related to a problem? Please describe.

<div class="col-md-3 mb-3">
                    <label class="" for='cpfcnpj'>CPF ou CNPJ</label>
                    <x-adminlte-input class="form-control" name='cpfcnpj' type='text'  />
</div>

### Describe the solution you'd like
Como eu aplico essa máscara para preencher este input acima?
mask '99.999.999/9999-99'

### Describe alternatives you've considered
Se não existir uma solução, o que vocÊ me recomenda fazer?

### Additional context
Desde já, agradeço pela atenção.

**Comment by cezarsanti** [comment]
<x-adminlte-input class="form-control" name='cpfcnpj' type='text' title='Informe o número do CPF ou do CNPJ'

**Comment by Shidersz** [comment]
Hi @cezarsanti , please next time use **English** language on your question. To add input masks you may use the next supported plugin of the **AdminLTE** template:

https://github.com/RobinHerbots/Inputmask/

First, read the plugin documentation to learn how to use it. Then, read next documentation to learn how to install it (since it is currently supported to be installed using our tools):

- [Plugin Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration)
- [The adminlte:plugins Artisan Command](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Artisan-Console-Commands#the-adminlteplugins-command)
