### ISSUE TITLE
[FEATURE] IFrame Mode Transitions

### ISSUE THREAD

**Issue by guidobri** [jeroennoten/Laravel-AdminLTE#989]
Would I be able to avoid this type of transition?

This spoils the entire user experience.

![ezgif-6-c8f0da7954b6](https://user-images.githubusercontent.com/91753830/135665948-4dea296d-e622-4532-9c19-392f5e0a62fa.gif)

Thanks for your attention.

**Comment by Shidersz** [comment]
Hi @guidobri Unfortunately, we can't tune this behaviour here, it is part of the underlying **AdminLTE** package, you may try incrementing the `loading_screen` option from `1000` to `2000` or more on the configuration file.

```php
    'options' => [
            'loading_screen' => 1000 /* <= THIS ONE */,
            'auto_show_new_tab' => true,
            'use_navbar_items' => true,
        ],
```

Maybe future versions of the **AdminLTE** package give us better experience on this feature...

**Comment by Guille47** [comment]
The problem is simple, when you call 

``` php
@extends('adminlte::page', ['iFrameEnabled' => true])
```
the loading tab is not being load, and the sencond problem is when you add it then you attach the menu code again, the solution for me is to separe the menu from the styles call, so you can call 

``` php
@extends('adminlte::page', ['iFrameEnabled' => true])
```

just in the very first page and then another section to attach just the styles.

**Comment by dfsmania** [comment]
We can't do anything about this here, the issue is related to the underlying **AdminLTE package**
